### ISSUE TITLE
OSV query API does not support querying by Linux versions. 

### ISSUE THREAD

**Issue by hyperlyz** [google/osv.dev#1000]
I use the api to analyze all the version for linux, but none worked.
A failure example is as follows.
cmd: curl -X POST -d   '{"version": "v6.0-rc6", "package": {"name": "Kernel", "ecosystem": "Linux"}}'   "https://api.osv.dev/v1/query"
result: {"code":504,"message":"upstream request timeout"}

**Comment by oliverchang** [comment]
Thanks for reporting this! We'll take a closer look into tomorrow Sydney hours as this appears to be limited to querying for Linux kernel issues with a version only. 

At a cursory glance, this may be because the number of Linux kernel matches for v6.0-rc6 is too numerous, and we need to come up with efficient indexing mechanism for this.

**Comment by oliverchang** [comment]
To validate this theory a bit more: 

- Querying in our version index for v6.0-rc6 returns 1000+ entries. 
- Querying for the latest versions (e.g. v6.2-rc6) returns an empty result instantly. 

There are two issues blocking this:
1. #1001 - to make the initial matching/querying more efficient
2. #151 - an older issue around making sure we can return large paginated responses. In this case there are 1000+ results to return which likely will run into some issues.

**Comment by hyperlyz** [comment]
> Thanks for reporting this! We'll take a closer look into tomorrow Sydney hours as this appears to be limited to querying for Linux kernel issues with a version only.
> 
> At a cursory glance, this may be because the number of Linux kernel matches for v6.0-rc6 is too numerous, and we need to come up with a more efficient indexing mechanism for this.

None of  Linux kernel worked, whichever version I use.

**Comment by oliverchang** [comment]
Sorry about that. This will take some time to properly resolve. We'll also see if there are any temporary workarounds we can provide to support Linux in the meantime also.
