### ISSUE TITLE
Add button to vulnerability UI to link to how to suggest an improvement

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1005]
On our detailed vulnerability page, we could link to a source-specific page for how a user can suggest an improvement.

E.g. for https://osv.dev/vulnerability/GHSA-2cxf-6567-7pp6, we can add a link to https://github.com/advisories/GHSA-2cxf-6567-7pp6/improve

**Comment by andrewpollock** [comment]
In a similar vein to this, I think some of our feedback has come via downstream consumers of our GCS-exported data.

Include a "README" or "FEEDBACK" or file of this nature in

1. the zip files
2. the per-ecosystem GCS bucket directories

that serves as a signpost to these pages that created as part of this issue.
