### ISSUE TITLE
Website latency reduction

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#1013]
I'll use this issue to collect some of the opportunities to improve page load time based on my attempts to measure latency for defining an SLO:

- https://tools.pingdom.com/#618e1f3848c00000

**Comment by zahraaalizadeh** [comment]
I'm planning to work on this one.

**Comment by zahraaalizadeh** [comment]
I just assessed the performance using Page Speed Insight:
https://pagespeed.web.dev/analysis/https-osv-dev/rsqqsi0hrn?form_factor=mobile

and it indicates potential room for improvement on the mobile version.

**Comment by zahraaalizadeh** [comment]
https://github.com/google/osv.dev/pull/2221
