### ISSUE TITLE
missing GHSA advisories

### ISSUE THREAD

**Issue by josieang** [google/osv.dev#1018]
There are some advisories that are in GitHub but not in OSV, @oliverchang mentioned that there might be some encoding issues but possible bugs as well.
```
GHSA-x4rg-4545-4w7w
GHSA-v62j-cxhh-fq22
GHSA-2w7w-2j92-44hx
GHSA-g2qw-6vrr-v6pq
GHSA-fj6c-prgj-gr3r
GHSA-5pg8-f89x-wjcx
GHSA-789v-h9hw-38pg
GHSA-wh77-3x4m-4q9g
```

**Comment by oliverchang** [comment]
Following up on this:

Thanks to @another-rex and @michaelkedar, 4 of these have been fixed (GHSA-v62j-cxhh-fq22, GHSA-g2qw-6vrr-v6pq, GHSA-5pg8-f89x-wjcx, GHSA-789v-h9hw-38pg)

The rest appear to be due to data quality issues from GitHub that we'll follow up on.

**Comment by oliverchang** [comment]
All affected GHSAs are now in the OSV.dev database.
