### ISSUE TITLE
missing OSS-Fuzz fixes 

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1019]
The OSS-Fuzz bisection infra failed to identify the fixes for:

https://osv.dev/vulnerability/OSV-2022-837 , https://osv.dev/vulnerability/OSV-2022-1173 , https://osv.dev/vulnerability/OSV-2023-49 , https://osv.dev/vulnerability/OSV-2022-1087 ,

**Comment by oliverchang** [comment]
For https://osv.dev/vulnerability/OSV-2022-1173, the bisector failed with:

```
Traceback (most recent call last):
  File "/usr/local/bin/oss_fuzz.py", line 129, in do_bisect
    result = bisector.bisect(bisect_type, old_commit, new_commit, f.name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 307, in bisect
    return _bisect(bisect_type, old_commit, new_commit, testcase_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 199, in _bisect
    bisect_repo_manager.fetch_all_remotes()
  File "/work/oss-fuzz/infra/repo_manager.py", line 134, in fetch_all_remotes
    self.git([
  File "/work/oss-fuzz/infra/repo_manager.py", line 59, in git
    return utils.execute(['git'] + cmd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/utils.py", line 73, in execute
    process = subprocess.Popen(command,
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/work/tmp/tmpadyhr3au/src/opensips'

Traceback (most recent call last):
  File "/usr/local/bin/oss_fuzz.py", line 129, in do_bisect
    result = bisector.bisect(bisect_type, old_commit, new_commit, f.name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 307, in bisect
    return _bisect(bisect_type, old_commit, new_commit, testcase_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 199, in _bisect
    bisect_repo_manager.fetch_all_remotes()
  File "/work/oss-fuzz/infra/repo_manager.py", line 134, in fetch_all_remotes
    self.git([
  File "/work/oss-fuzz/infra/repo_manager.py", line 59, in git
    return utils.execute(['git'] + cmd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/utils.py", line 73, in execute
    process = subprocess.Popen(command,
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/work/tmp/tmpadyhr3au/src/opensips'

```

**Comment by oliverchang** [comment]
Similar story for https://osv.dev/vulnerability/OSV-2023-49

**Comment by oliverchang** [comment]
Digging a bit deeper, this seems to be closer to the root cause: 

```
INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -v /tmp/tmpnpk98t4f:/out gcr.io/oss-fuzz/opensips cp -r -p /src /out.
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: creating container: cannot create sandbox: cannot read client sync file: waiting for sandbox to start: EOF: unknown.```

**Comment by oliverchang** [comment]
Running Docker with `--privileged` seems to be broken on GKE:

```
root@workers-6544998464-ngqmb:/work/oss-fuzz/infra# docker run --rm -ti --privileged ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
677076032cca: Pull complete 
Digest: sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
Status: Downloaded newer image for ubuntu:latest
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: creating container: cannot create sandbox: cannot read client sync file: waiting for sandbox to start: EOF: unknown.
```

This is not reproducible locally with the exact same worker Docker image.

**Comment by oliverchang** [comment]
I tried debugging on GKE by manually creating a Pod with the exact same worker image and k8s config. I then added some debug flags to runsc/gVisor and now I see:

```
W0213 06:24:15.327947     483 util.go:49] FATAL ERROR: creating loader: converting capabilities: unknown capability "CAP_PERFMON"
creating loader: converting capabilities: unknown capability "CAP_PERFMON"
```

Looks like an underlying kernel change may have caused this.

**Comment by inferno-chromium** [comment]
> For https://osv.dev/vulnerability/OSV-2022-1173, the bisector failed with:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/oss_fuzz.py", line 129, in do_bisect
>     result = bisector.bisect(bisect_type, old_commit, new_commit, f.name,
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/work/oss-fuzz/infra/bisector.py", line 307, in bisect
>     return _bisect(bisect_type, old_commit, new_commit, testcase_path,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/work/oss-fuzz/infra/bisector.py", line 199, in _bisect
>     bisect_repo_manager.fetch_all_remotes()
>   File "/work/oss-fuzz/infra/repo_manager.py", line 134, in fetch_all_remotes
>     self.git([
>   File "/work/oss-fuzz/infra/repo_manager.py", line 59, in git
>     return utils.execute(['git'] + cmd,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/work/oss-fuzz/infra/utils.py", line 73, in execute
>     process = subprocess.Popen(command,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/work/tmp/tmpadyhr3au/src/opensips'
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/worker.py", line 565, in _do_process_task
>     oss_fuzz.process_bisect_task(self._oss_fuzz_dir, task_type, source_id,
>   File "/usr/local/bin/oss_fuzz.py", line 175, in process_bisect_task
>     if result.repo_url in REPO_DENYLIST:
>        ^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'repo_url'
> ```

Do we get stackdriver exceptions for these ? That way sheriff can watch those every week and see these ones and others from time to time ?

**Comment by oliverchang** [comment]
> > For https://osv.dev/vulnerability/OSV-2022-1173, the bisector failed with:
> > ```
> > Traceback (most recent call last):
> >   File "/usr/local/bin/oss_fuzz.py", line 129, in do_bisect
> >     result = bisector.bisect(bisect_type, old_commit, new_commit, f.name,
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/work/oss-fuzz/infra/bisector.py", line 307, in bisect
> >     return _bisect(bisect_type, old_commit, new_commit, testcase_path,
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/work/oss-fuzz/infra/bisector.py", line 199, in _bisect
> >     bisect_repo_manager.fetch_all_remotes()
> >   File "/work/oss-fuzz/infra/repo_manager.py", line 134, in fetch_all_remotes
> >     self.git([
> >   File "/work/oss-fuzz/infra/repo_manager.py", line 59, in git
> >     return utils.execute(['git'] + cmd,
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/work/oss-fuzz/infra/utils.py", line 73, in execute
> >     process = subprocess.Popen(command,
> >               ^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: '/work/tmp/tmpadyhr3au/src/opensips'
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/bin/worker.py", line 565, in _do_process_task
> >     oss_fuzz.process_bisect_task(self._oss_fuzz_dir, task_type, source_id,
> >   File "/usr/local/bin/oss_fuzz.py", line 175, in process_bisect_task
> >     if result.repo_url in REPO_DENYLIST:
> >        ^^^^^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'repo_url'
> > ```
> 
> Do we get stackdriver exceptions for these ? That way sheriff can watch those every week and see these ones and others from time to time ?

Yes this is a wider issue we've had for some time -- these exceptions are not getting propagated properly to the error reporting. Will track this.

**Comment by oliverchang** [comment]
I incorrectly assumed that the downgrade would fix things here. It's still failing with the same error, and is likely more due to the newer kernel version instead of Docker itself.

**Comment by oliverchang** [comment]
I take back my previous statement. It was indeed the Docker version -- I just hadn't downgraded it far back enough.

**Comment by oliverchang** [comment]
All reported entries now have fixes included.
