### ISSUE TITLE
Use OSV to scan a private GitHub repo? Or scan a locally cloned repo?

### ISSUE THREAD

**Issue by keypointt** [google/osv.dev#1045]
Maybe a stupid question, but I tried it against my private github repo and returned is empty, due to the permission to access this repo.

```
{}(base) xin@xinUbuntu:~/Downloads$ curl -X POST -d \
>   '{"version": "1.0.0",
>     "package": {"name": "my_private_repo", "ecosystem": "PyPI"}}' \
>   "https://api.osv.dev/v1/query"
{}
```

Is it possible to scan a private github repo or a local repo on my laptop that is never published to the internet?

I'm thinking of using something like `curl -u username:password http://example.com` to provide credentilas to access a private repo, but just double check OSV is not saving my credentials in your database? :P

Thank you!

**Comment by oliverchang** [comment]
Hi, 

Our API is only for checking if a specified package has any known vulnerabilities. 

To check generally if a project **depends** on any vulnerable packages, check out https://github.com/google/osv-scanner

**Comment by keypointt** [comment]
cool thank you Oliver :+1:
