### ISSUE TITLE
Add RSS link to blog

### ISSUE THREAD

**Issue by hayleycd** [google/osv.dev#1048]
Currently we have an RSS feed, but we do not have a link that shows up on the blog.

**Comment by ZhangChen199102** [comment]
I'd like to pick this issue up.
(leaving a comment here as I'm unable to assign issue to myself)

**Comment by andrewpollock** [comment]
Thanks @ZhangChen199102 please ensure you've reviewed https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md and any feedback on our first time contributor onboarding is very welcome :-)
