### ISSUE TITLE
data: add ecosystem list/manifest

### ISSUE THREAD

**Issue by hdonnay** [google/osv.dev#1054]
I'd like to download the `all.zip` dumps. The current way I do this is to list the bucket and look for keys ending in `all.zip`. This takes 77 (S3 API) requests currently and will only get larger over time. Having a manifest of ecosystem names at a well-known key would cut this number to 1.

Alternatively, having the zips available at a second, "rotated" key (like `npm/all.zip` also being at `all/npm.zip`) would work but I think a second copy of the all.zip would be easy to have fall out of sync.

It's also possible there's some other way to get a list of the "all.zip" files that I'm missing.

**Comment by oliverchang** [comment]
Hi, there is an `ecosystems.txt` file available which lists every single ecosystem available: https://osv-vulnerabilities.storage.googleapis.com/ecosystems.txt

You can use this to construct all.zip links.

**Comment by hdonnay** [comment]
Ah, I missed that -- Thanks!

**Comment by andrewpollock** [comment]
@hdonnay is there an opportunity to up-level our documentation here to have made this more discoverable?

**Comment by hdonnay** [comment]
Yeah, #1056 is exactly what I'd suggest :+1:
