### ISSUE TITLE
data: "fixed" before "introduced" is very odd

### ISSUE THREAD

**Issue by hdonnay** [google/osv.dev#1055]
The osv representation of [GHSA-28f8-hqmc-7ph8](https://github.com/advisories/GHSA-28f8-hqmc-7ph8) represents the version constraints as:
```
     "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {"introduced": "1.0.8"},
            {"fixed": "1.0.7"}
          ]
        }
      ],
```

This seems wrong -- you can't fix something before it's introduced. This is more akin to blocklisting a release. Shouldn't this be represented as something like `{"introduced": "1.0.8"},{"limit":"1.0.8"}` ?

**Comment by oliverchang** [comment]
Hi! Thanks for raising this. Looks like this is an issue on GitHub's side. I've opened https://github.com/github/advisory-database/pull/1712 to address this.

**Comment by andrewpollock** [comment]
+1, thank you for raising this. I'm working on #771 and I hadn't considered this particular scenario, so it's a very timely callout.

**Comment by hdonnay** [comment]
Fine, here's some activity.

**Comment by another-rex** [comment]
I believe this is fixed, in the upstream source, a single specific release is specified to be affected.
