### ISSUE TITLE
Add a new data source contributor guide

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#1073]
Make learning how to contribute a new data source discoverable and documented. Primary example use case "I am a Linux Distribution and want to contribute my security advisories in OSV format to OSV"

This could conceivably be added to the FAQ.

Questions that should be answered:

- How do I supply my data?
  - Git repo or GCS bucket
- How do I correctly generate my data?
  - Refer out to OSV Schema documentation and validation tooling
- How do I get my data imported by OSV.dev?
  - Direct to file a new GitHub Issue tagged `datasource`

**Comment by hayleycd** [comment]
#1079 addresses the issue, but we may want to include info on the OSV.dev website as well, and #1079 only addresses it in the readme.

**Comment by andrewpollock** [comment]
> #1079 addresses the issue, but we may want to include info on the OSV.dev website as well, and #1079 only addresses it in the readme.

I think a pointer in the FAQ to the relevant README sections would be sufficient to cross-reference the two and reduce ongoing maintenance.

**Comment by hayleycd** [comment]
I am closing this. We have now updated CONTRIBUTING.md, the README, and the FAQ portion of the site to point to the changes.
