### ISSUE TITLE
Support OSV Schema 1.4.0

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1093]
The two main changes are described in https://ossf.github.io/osv-schema/#change-log:

- A new per-package severity field. 
- A new credit types enum field. 

We just need to add these to our protobuf definitions

**Comment by oliverchang** [comment]
@michaelkedar can you please take a stab at this? 

GitHub has started to make use of this: https://github.blog/changelog/2023-03-07-security-advisories-now-have-multiple-types-of-credits/

**Comment by jayvdb** [comment]
https://github.com/google/osv.dev/pull/1115 was merged. Is there more to do, or can this be closed?

**Comment by oliverchang** [comment]
Thanks, closed.
