### ISSUE TITLE
PYSEC-2018-53 was not removed from the data

### ISSUE THREAD

**Issue by donchkat** [google/osv.dev#1098]
When I search for PYSEC-2018-53 in the website it does not exist. 
Yet it exists in the API response when I consume PYPI data from here:
https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip
I assume it was removed because of the incorrect name in the package name? And yet it exists in the API response with the incorrect package name (f-ask and not flask)
<img width="543" alt="image" src="https://user-images.githubusercontent.com/74149435/223107680-21b76de8-96df-42f0-9bd6-7bddbee156a0.png">

Let me know if I'm missing something, Thanks.

**Comment by donchkat** [comment]
Got it. About the last point, do you think the `withdrawn` field will be added to PYSEC-2018-53 sometime in the future, so I will be able to filter it out from my database?

**Comment by andrewpollock** [comment]
@donchkat yes, I'll get the erroneous records tidied up in the very near future.

**Comment by andrewpollock** [comment]
Keeping this open until the data gets fixed

**Comment by andrewpollock** [comment]
I have made a number of fixes to our data, and these should be reflected in the exports that you are consuming in approximately 5 hours from time of writing.

If you still observe any data quality issues after this, please reopen this with specifics and I will investigate further.
