### ISSUE TITLE
Consider styling options for blog

### ISSUE THREAD

**Issue by hayleycd** [google/osv.dev#1106]
@olivekl and I are a little concerned that the website's styling is not a great fit for long form blog posts. The home page is beautiful, but the scheme is less effective for a blog post where readers are going to spend longer periods of time focused on the text. 

We wanted to open the issue to discuss possible changes that could be made to make the text a little friendlier on the eyes when reading longer form content.

**Comment by oliverchang** [comment]
Indeed there are likely many improvements to be made here. 

Do you have any suggestions to kick this off?

**Comment by hayleycd** [comment]
I think the line spacing is a little tight. If you compare it to something like the google security blog, you can really see the difference. That is an easy fix that could make a large difference. 

I think it would be interesting to try a different font. I also am not fully happy with how links are formatted (with the little icon instead of a different color) because when the link color is different it can kind of break up the text a little.

**Comment by olivekl** [comment]
+1 to line spacing and font. I'm also not sure about whether the white on black is contributing, but maybe the font and spacing changes would fix the readability issue enough on its own.

**Comment by hayleycd** [comment]
We made some preliminary changes with #1228. After #1228 was merged we received additional feedback from our designer, so related issues are captured in #1245.
