### ISSUE TITLE
Interested towards Ubuntu datasource addition for osv.dev

### ISSUE THREAD

**Issue by manumayur1234** [google/osv.dev#1113]
Dear All,

I could not see ubuntu eco system support in osv.dev
So, I am interested to know about the process of adding ubuntu data-base to osv.dev and I wish to support in this.
Also I would like to know if there is any development going on regarding this.

Thanks & Regards,

**Comment by andrewpollock** [comment]
Hi @manumayur1234 thanks for your interest in adding Ubuntu security advisories as a datasource.

https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md#contributing-data is our initial attempt at documenting how to get started. Any feedback on how to make it more actionable is appreciated.

In a nutshell, you need to provide records for Ubuntu's security advisories in the [OSV Schema format](https://ossf.github.io/osv-schema/), either via a public GCS bucket or a Git repository.

You need to send us a PR to add a new ID prefix to https://github.com/ossf/osv-schema/blob/main/docs/schema.md#id-modified-fields

Once we've validated your source is correctly formed, we'll set OSV.dev up to import from it on an ongoing basis, and we're good to go.

You may find https://github.com/ossf/osv-schema/tree/main/tools/debian useful for inspiration.

Please let us know if you have any further questions.

**Comment by MikeMoore63** [comment]
I can see Ubuntu database now appears to have osv format data https://github.com/canonical/ubuntu-security-notices/tree/main/osv . I also saw 1.6.2 schema added Ubuntu ecosystem so anyone know is this being progressed and is plan to add it or should consumers be looking at getting data directly?

**Comment by oliverchang** [comment]
Hi! Thanks for the interest. @dodys from Canonical has been working on OSV support here: https://github.com/canonical/ubuntu-security-notices/tree/main/osv.

We'll work on importing this into OSV.dev shortly.

**Comment by MikeMoore63** [comment]
I can see data is now available is this closed now or open still for a reason?

If it is be interested to know what that reason might be.

Thanks

Mike

**Comment by andrewpollock** [comment]
I think we can close this out.
