### ISSUE TITLE
Add API ability to enumerate database to create local copies

### ISSUE THREAD

**Issue by gitgitwhat** [google/osv.dev#1124]
Related to #546 and similar how NVD (https://nvd.nist.gov/developers/vulnerabilities) allows you to paginate CVEs (lastModStartDate & lastModEndDate).  It would be nice if the OSV.dev API had the same ability so local copies of the database can be made.

**Comment by oliverchang** [comment]
Hi! We already have data dumps available here: https://github.com/google/osv.dev#data-dumps

Does this work for your use ase?

**Comment by gitgitwhat** [comment]
I can make it work but something a little cleaner such as the NVD method would be useful.  The description says "continuously" but is that quantified anywhere?  How often do I need to query for updates?

**Comment by oliverchang** [comment]
This will be part of our SLO which will be published very soon. CC @andrewpollock

**Comment by andrewpollock** [comment]
FYI, SLO is published as an entry at https://osv.dev/faq (sadly I cannot deep-link to it)
A related blog post will be live on https://osv.dev/blog next week.

**Comment by andrewpollock** [comment]
I think an API-based mechanism for obtaining the data is unlikely to be a priority for us, given the exports should be good enough for most people.

- https://google.github.io/osv.dev/faq/#is-the-database-available-to-download
- https://google.github.io/osv.dev/data/#data-dumps
- https://google.github.io/osv.dev/faq/#what-are-osvs-service-level-objectives-slos
