### ISSUE TITLE
Invalid purls

### ISSUE THREAD

**Issue by gitgitwhat** [google/osv.dev#1234]
I've found a number of records where the purls are not properly formatted.

PYSEC-2021-872 is one example.  The purl in that record is `pkg:pypi:distributed` which is not valid (second colon should be a slash). 

Here's the purl spec for reference:
https://github.com/package-url/purl-spec

**Comment by satanshiro** [comment]
I have also noticed an issue regarding debian purls, if you add distro to the purl then from what i've it is ignored, also arch=source is problematic as it automatically disqualifies querying by a specific architecture i.e. arm64
example: 
    "package": {
        "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?distro=debian-8"
    }
will ignore the distro query and return the vulnerabilities
and querying 
    "package": {
        "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64"
    }
will result with empty object
this is the purl returned by osv
![image](https://github.com/google/osv.dev/assets/38865738/595e7e7e-20be-4f0f-946b-2d32bdaacbc9)

**Comment by andrewpollock** [comment]
@satanshiro I'll fork your comment out into a separate issue because it's a different data source with likely very different solutions to the original issue raised here.

**Comment by andrewpollock** [comment]
@gitgitwhat were you observations limited to the Python ecosystem, or broader?
