### ISSUE TITLE
Add support for a REST API endpoint as a datasource

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#1235]
Rocky Linux has started publishing OSV records via a REST API interface, which is not a supported consumption mechanism at present.

There's value in supporting a feed via a REST API, as this gives future data publishers more publication options than just a Git repo or a GCS bucket.

**Comment by oliverchang** [comment]
This will also be useful for curl, who are currently publishing their OSV feed at https://curl.se/docs/vuln.json

**Comment by jess-lowe** [comment]
Closed in #1901
