### ISSUE TITLE
version parameter in query request to query for the latest version

### ISSUE THREAD

**Issue by aswinnnn** [google/osv.dev#1243]
I'm currently making a tool that depends on API calls to OSV.
The availability of a specific version number is questionable so I'd like to propose a "latest" keyword for the version parameter so it can return the vulnerabilities for the latest version number added to the database of the package.

an example:
```bash
curl -X POST -d \
  '{"version": "latest",
    "package": {"name": "jinja2", "ecosystem": "PyPI"}}' \
  "https://api.osv.dev/v1/query"
```

I'm not sure OSV might be aware of the latest version of any package so this could return the entries in the database with the greatest version number that it knows of instead.

**Comment by oliverchang** [comment]
Hi, this is likely fairly infeasible for us to implement unfortunately. If you want to get the latest version of a package in an easy, consistent way, I'd recommend checking out https://docs.deps.dev/api/v3alpha/
