### ISSUE TITLE
Support AlmaLinux ecosystem enumeration

### ISSUE THREAD

**Issue by michaelkedar** [google/osv.dev#1274]
Need to implement an [ecosystem helper for AlmaLinux](https://github.com/google/osv.dev/blob/d14f916b46768749da4d92d76d322c91e81dd23b/osv/ecosystems/_ecosystems.py#L72-L74) to parse version strings and fetch versions of packages.

**Comment by oliverchang** [comment]
This is no longer relevant due to #2401
