### ISSUE TITLE
How to use OSV scanner for Hugo project

### ISSUE THREAD

**Issue by karthik-hr** [google/osv.dev#1292]
For hugo projects we dont have any yarn.lock. How can we use OSV scanner to find vulnerability on the external dependency loaded using <script> tags

**Comment by hayleycd** [comment]
Hi @karthik-hr!

You can read more about our currently supported lockfiles [here](https://google.github.io/osv-scanner/usage/#specify-lockfiles). Currently OSV-Scanner cannot read dependencies from <script> tags. If that is a feature you would like to see, you can always open an issue in the [OSV-Scanner repo](https://github.com/google/osv-scanner/issues/new) for it to be considered. 

There are other ways you can access vulnerability information besides using OSV-Scanner. You can manually [search our database](https://osv.dev/list) for the packages you are using, or you can use our [API](https://google.github.io/osv.dev/api/).
