### ISSUE TITLE
osv-scanner reporting timeout

### ISSUE THREAD

**Issue by jayvdb** [google/osv.dev#1363]
For about an hour we've been seeing the following from `osv-scanner`.

> failed to hydrate OSV response: server response error: {"message":"upstream request timeout","code":504}

This is odd because the web UI at https://osv.dev seems to be fully operational.

**Comment by oliverchang** [comment]
Thank you very much for the report. We'll investigate this. Are you able to share what your lockfiles/repos look like? Are you scanning any git repos/submodules?

**Comment by jayvdb** [comment]
We have Rust repos scanning a Cargo.lock file

**Comment by oliverchang** [comment]
Thanks. Is there any chance you'd be able to share the lockfile with us to assist us with debugging this? We're not seeing this with all of our API responses.

**Comment by jayvdb** [comment]
We are using private cloudsmith repos for a few of the dependencies in these Cargo.lock files.  Might be related.

I can send the Cargo.lock privately, but can not see an email address on the website or repo for sending private stuff.  Feel free to reach out to me on the email address on my github profile.

**Comment by oliverchang** [comment]
thanks! sent!

**Comment by oliverchang** [comment]
Thanks a ton @jayvdb ! The team has pushed out a mitigation for the API issues you were encountering, and we will be going through a postmortem to prevent this from happening again in the future. 

Please let us know if you are still experiencing this.
