### ISSUE TITLE
Support RedHat vulnerabilities

### ISSUE THREAD

**Issue by fingeromer** [google/osv.dev#1404]
Currently OSV supports a few operating system ecosystems like Debian & Alpine. 
We would like to open a feature request for supporting RedHat ecosystem vulnerabilities. 

Thanks, have a nice day.

**Comment by mprpic** [comment]
The Red Hat ecosystem is large and varied so we're still working out the kinks on how to best structure the data in the OSV schema, but it's in progress! Since there is interest in this data, I'll ask here @fingeromer, are you mostly interested in data on vulnerabilities affecting RPMs shipped on RHEL? Or other Red Hat products as well?

**Comment by andrewpollock** [comment]
The onboarding process is a little bit bespoke and toilsome at the moment, but something we're continuously improving on and streamlining with each new data source onboarded. I would like to get it to the point of being much more checklist/cookbook driven than it currently is. My detailed response here is an (ongoing) experiment at further process improvement and seeks to address some [recent actionable feedback received by another data source onboarding](https://github.com/google/osv.dev/issues/2089#issuecomment-2071549142). Your actionable feedback is also very welcome.

In a nutshell:

- [ ] Decide if you're going to publish records via a Git repository, GCS bucket or [REST endpoint](https://google.github.io/osv.dev/rest-api-contribution/) (I'm going to assume a Git repository?)
- [ ] Create a PR to [reserve a prefix in the OSV-Schema](https://ossf.github.io/osv-schema/#id-modified-fields) (worked examples: https://github.com/ossf/osv-schema/pull/235 https://github.com/ossf/osv-schema/pull/223 https://github.com/ossf/osv-schema/pull/219)
  - [ ] We review the records you start publishing for OSV Schema [correctness](https://github.com/ossf/osv-schema/tree/main/validation) and [quality](https://google.github.io/osv.dev/data_quality.html) (the work happening under the [OSV Data Quality Program](https://github.com/orgs/google/projects/62) is also relevant here, as an FYI) as part of reviewing and merging that PR
- [ ] Create a PR to extend [purl_helpers.py](https://github.com/google/osv.dev/blob/master/osv/purl_helpers.py) (if appropriate)
- [ ] Create a PR to start [importing the records you are publishing into our test instance of OSV.dev](https://github.com/google/osv.dev/blob/master/source_test.yaml) and validate everything is working as intended there (worked example: https://github.com/google/osv.dev/pull/2086)
- [ ] Create a PR to start [importing the records you are publishing into our production environment](https://github.com/google/osv.dev/blob/master/source.yaml) (worked example: https://github.com/google/osv.dev/pull/2105)

**Known onboarding rough edges**:
- the format of the `source{,_test}.yaml` files (hopefully the example PRs plus other existing entries will make this reasonably self-evident). Specifically, FYI, the value for `type` corresponds with those defined at https://github.com/google/osv.dev/blob/381f459de12e181447731beee9ba4b06a513c586/osv/models.py#L783-L787

**Comment by jasinner** [comment]
We going to publish the records at a new REST endpoint `https://access.redhat.com/security/data/osv/`

[Add Red Hat Ecosystem in osv-schema repo.](https://github.com/ossf/osv-schema/pull/257)

**Comment by jasinner** [comment]
I guess we don't need to adjust purl_helpers because we include purls with our OSV records.

**Comment by andrewpollock** [comment]
> I guess we don't need to adjust purl_helpers because we include purls with our OSV records.

Correct.

**Comment by jasinner** [comment]
Reserved an ecosystem prefix [Red Hat](https://github.com/ossf/osv-schema/pull/257)

**Comment by oliverchang** [comment]
Indeed! Thanks again @jasinner @mprpic for making this happen!
