### ISSUE TITLE
Document osv-vulnerabilities directory structure. 

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1417]

**Comment by hayleycd** [comment]
Can you provide more context?

**Comment by oliverchang** [comment]
The current documentation lacks a bit of detail on what ecosystems with ":" in them means. e.g. "Debian:X". Certain ecosystems are split by release numbers, and we export both the inidividual "Debian:X" as well as an aggregated "Debian" that contains all releases.

**Comment by andrewpollock** [comment]
> The current documentation lacks a bit of detail on what ecosystems with ":" in them means. e.g. "Debian:X". Certain ecosystems are split by release numbers, and we export both the inidividual "Debian:X" as well as an aggregated "Debian" that contains all releases.

It looks like this specifically was done in https://github.com/google/osv.dev/pull/2036
