### ISSUE TITLE
add HSEC (Haskell) security advisories data source

### ISSUE THREAD

**Issue by frasertweedale** [google/osv.dev#1418]
The Haskell community is establishing a security advisory database: https://github.com/haskell/security-advisories .
We are currently bootstrapping the database with known vulnerabilities and developing our tooling and processes.

OSV export is nearly complete.  Of course, we would like osv.dev to ingest our data.

Could you please advise next steps?  What is the best way to publish our OSV data for osv.dev to ingest and process it?

I couldn't easily make sense of the OSV importer code or where the sources are configured.  But from what I can see,
it looks like a Git branch containing *just* the individual OSV json files for each of our advisories would be easy for you to
consume?  If you prefer something else please elaborate.

Thanks!

Fraser
on behalf of the Haskell Security Response Team

**Comment by oliverchang** [comment]
Hey there! This is super exciting, thanks for filing this issue.  Sorry for the lack of detailed documentation on this. 

Indeed, a git repo with a branch containing OSV JSONs would work great for us. One additional piece here to make our API matching and indexing work is to add support for version ordering and enumeration in https://github.com/google/osv.dev/blob/1d395c94739bd50b919b21a1642f8fe4d697b539/osv/ecosystems/_ecosystems.py#L28. This doesn't block the initial ingestion, but it does make API queries work. 

Does Hackage/Haskell use its own versioning scheme, or does it follow something like SemVer 2.0 strictly? New ecosystems that follow SemVer can be added very easily with minimal work.

**Comment by frasertweedale** [comment]
> Does Hackage/Haskell use its own versioning scheme, or does it follow something like SemVer 2.0 strictly? New ecosystems that follow SemVer can be added very easily with minimal work.

Haskell package versions are not SemVer.  They allows an arbitrary number (> 1) of version number components, and there are no optional labels.  Comparison logic is more or less what you'd expect, with the one quirk that e.g. `1.2.` < `1.2.0`.

**Comment by oliverchang** [comment]
Thanks for clarifying. Is there a spec describing the Haskell package version scheme? Is https://pvp.haskell.org/ the one?

**Comment by frasertweedale** [comment]
https://pvp.haskell.org/ has all the necessary info, but I would call it "informational".  The closest thing to a normative specification is the doc and source code of https://hackage.haskell.org/package/Cabal-syntax-3.10.1.0/docs/Distribution-Types-Version.html .

**Comment by frasertweedale** [comment]
I have a separate thing to mention: our database will include advisories for multiple ecosystems: currently `Hackage` (think PyPI but for Haskell) and `GHC` (the compiler ecosystem) - as defined in https://github.com/ossf/osv-schema/pull/157 (which you merged ^_^).  Is it supported for a single data source to supply advisories for multiple ecosystems?

**Comment by oliverchang** [comment]
> I have a separate thing to mention: our database will include advisories for multiple ecosystems: currently `Hackage` (think PyPI but for Haskell) and `GHC` (the compiler ecosystem) - as defined in [ossf/osv-schema#157](https://github.com/ossf/osv-schema/pull/157) (which you merged ^_^). Is it supported for a single data source to supply advisories for multiple ecosystems?

That's totally fine!

**Comment by frasertweedale** [comment]
Thanks @oliverchang.  I'll let you know when our OSV export branch is ready.  (Probably in the next couple of weeks).

**Comment by frasertweedale** [comment]
@oliverchang we got it done quicker than expected.  Here's our OSV branch:
https://github.com/haskell/security-advisories/tree/generated/osv-export .

If there are any bugs/quirks/deficiencies in the OSV we generate, please let us know and we will endeavour to fix it promptly!

**Comment by oliverchang** [comment]
Nice! We've started the ingestion into our test instance, now visible here: https://oss-vdb-test.appspot.com/list?ecosystem=Hackage

**Comment by oliverchang** [comment]
These are now in our prod instance: https://osv.dev/list?ecosystem=Hackage.

That said, we're still lacking enumeration support (https://github.com/google/osv.dev/issues/1418#issuecomment-1608791403) so these won't be returned by any API queries yet.

**Comment by frasertweedale** [comment]
@oliverchang thanks for the update.  I'll turn my attention to the ecosystem-specific bits in the next week or so.  Cheers!

**Comment by frasertweedale** [comment]
@oliverchang first cut: https://github.com/google/osv.dev/pull/1463.  Hopefully I put the right bits in the right place.
