### ISSUE TITLE
New ecosystems support

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1438]
Metaissue to collect all the outstanding sources there are where we don't have full support:

| Source | Imported | Indexed |
|------------|---------------|----------------|
| Rocky Linux | ✓ | #1275 |
| AlmaLinux | ✓ | #1274 |
| Curl | ✓ | N/A (git) |
|Haskell | ✓ | ✓ |
| Hex | ✓ (from GHSA) | N/A (SemVer) | 
| Bitnami | ✓ | N/A (SemVer) |

**Comment by andrewpollock** [comment]
> I think Haskell now has full support, right?

Yes, edited to reflect current state

**Comment by andrewpollock** [comment]
If I'm reading https://github.com/google/osv.dev/blob/7c3e1e065668acd1fb06b56f1f2a0137bf3e6852/osv/ecosystems/_ecosystems.py#L60-L66 correctly, this is the outstanding list.

**Comment by oliverchang** [comment]
Closing this as much of this has been addressed by https://github.com/google/osv.dev/issues/2401
