### ISSUE TITLE
Set up a cleanup cron job that checks all the entries in the database for existance

### ISSUE THREAD

**Issue by another-rex** [google/osv.dev#1467]
Checks the source field in the database to see if they still exist (does not return 404), if not, mark it as withdrawn.

**Comment by rajbhoyar729** [comment]
Can you assign me this issue i want to work on it

**Comment by another-rex** [comment]
Hey @rajbhoyar729, sorry missed this comment for a long time. This is more of a internal task as you would need access to the database backend to be able to adequately  work on it.

**Comment by another-rex** [comment]
#1859 is another example of this being potentially useful.

**Comment by rajbhoyar729** [comment]
Can you guide me how can I do it

**Comment by andrewpollock** [comment]
@rajbhoyar729 your enthusiasm for contributing to OSV has been noticed 🥇 
This particular issue is difficult for external contributors who don't have access to our GCP infrastructure (that's what we cooked up the `needs-gcp-infra-access` to.

Please take a look at [the issues tagged with `good first issue`](https://github.com/google/osv.dev/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). These are more suitable for folks like yourself. You may also like to [contribute to OSV Scanner](https://github.com/google/osv-scanner/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

Stay enthusiastic!

**Comment by andrewpollock** [comment]
Manually ran this in Production:

```
5220 Bugs in Datastore considered deleted from GCS for cve-osv
23 Bugs in Datastore considered deleted from GCS for debian-dsa
19 Bugs in Datastore considered deleted from GCS for go
```

**Comment by andrewpollock** [comment]
I think we can call this done finally.
