### ISSUE TITLE
Questions about pagination

### ISSUE THREAD

**Issue by SouravJohar** [google/osv.dev#1474]
I came across the documentation around pagination. I have a few questions:

1. How many vulnerability entries can a single page contain? Is this number the same for both the query API as well as the batchquery API?
2. Is the page size configurable?
3. When will the pagination support go live?

Thanks!

**Comment by hayleycd** [comment]
Hi @SouravJohar !

To answer your questions:

1. The page size for `/v1/query` is 1,000. For `/v1/batchquery` each individual query within the batch has a max of 1,000 and the max for the query batch is 3,000. 
2. The page size is not configurable. 
3. Pagination is currently live for batch query, but we have currently disabled a few larger individual queries. We will be turning them back on soon at which point pagination will be live for `/v1/query` as well. For more info on the disabled query see [our faq](https://google.github.io/osv.dev/faq/#why-am-i-getting-an-error-message-for-my-linux-kernel-query)

**Comment by SouravJohar** [comment]
Thanks for the quick response!

A followup: When you say the max for the query batch is 3000 - do you mean that the maximum number of packages that can be queried in a single batch is 3000?

Or do you mean that the maximum number of vulnerabilities would be 3000 per page?

**Comment by hayleycd** [comment]
I mean that it will only return 3,000 total vulns at a time. After 3,000 vulns, you'll start getting `next_page_token` and need to make additional calls using the page tokens to view all of the vulns.
