### ISSUE TITLE
Normalize package versions for querying

### ISSUE THREAD

**Issue by michaelkedar** [google/osv.dev#1516]
Currently, for non-semver ecosystems, version numbers in queries only work if they are exactly what is listed on the package manager.

Some ecosystems allow for multiple ways to refer to a specific version e.g. in PyPI installing `django==4.2.0` will install [`Django==4.2`](https://pypi.org/project/Django/4.2/). (in fact, you can specify any number of trailing `.0`'s and it will install the same version)
Querying the OSV API for django 4.2.0 yields no results, even though django 4.2 does have vulnerabilities.

We need to normalize versions both when ingesting and on the API when querying so we can match these cases.

**Comment by oliverchang** [comment]
I suppose we can use https://packaging.pypa.io/en/latest/utils.html#packaging.utils.canonicalize_version for this.

@michaelkedar do you know of any other ecosystems that have this issue?

@cuixq may be an interesting starter project for osv.dev infra.

**Comment by oliverchang** [comment]
Per https://github.com/google/osv.dev/discussions/1673 this may be an issue for NuGet as well.
