### ISSUE TITLE
Minor issues with Debian advisories

### ISSUE THREAD

**Issue by rhalar** [google/osv.dev#1525]
A few of the Debian advisories which get parsed end up with a nonsensical `<not-affected>` fixed version in the affected range, e.g.
https://osv.dev/vulnerability/DSA-226
https://osv.dev/vulnerability/DSA-177

This seems to happen when a version of a distribution is, well, not affected but still seems to issue an advisory for it to explicitly state it is safe. These are all for very old distributions though.
But perhaps some validation for the versions which end up in ranges and affected versions could be added? I'm not sure if it is strictly enforced but Debian does have a specification on how versions should be structured:
https://www.debian.org/doc/debian-policy/ch-controlfields.html#version

Furthermore, some of the `source` links do not resolve; they return a `NoSuchKey` error. That is the case for the two DSAs linked above, but I haven't looked into others.
Both end up in the data dumps though.

**Comment by andrewpollock** [comment]
@another-rex it seems like the right course of action for ones like described here not to generate anything at all?

**Comment by andrewpollock** [comment]
In fact, it looks like that was the intent of https://github.com/ossf/osv-schema/pull/56

Do we just need to remove these historically generated vulnerabilities?

**Comment by another-rex** [comment]
Yep that should fix it, those entries don't exist anymore in the bucket, but we juts don't have a process to automatically clean them up. #1467

**Comment by andrewpollock** [comment]
@rhalar in the interim until #1467 gets worked on (or perhaps you might like to work on it?), if you would like to review the Debian export (see https://google.github.io/osv.dev/data/#data-dumps) and provide an exhaustive list of the Debian advisories that need to be removed, we can do a one-time manual removal, given that no more should be introduced.

**Comment by rhalar** [comment]
I haven't been able to track down any other examples except the two mentioned above, `DSA-226` and `DSA-177`. I don't think it's a widespread issue, it just caught my eye that perhaps versions could be validated since they are mentioned in the Debian spec.

**Comment by andrewpollock** [comment]
I have manually deleted the entries for `DSA-226` and `DSA-177` from the database. Thank you for helping keep OSV's data quality high!

**Comment by rhalar** [comment]
Great, thanks!
