### ISSUE TITLE
Add a custom 404 page

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#1556]
OSV.dev's 404 page should be more thematically consistent (and perhaps Googley at the same time) with the rest of the OSV.dev website.

**Comment by andrewpollock** [comment]
I was thinking something in the vein of "Zarro Boogs"

**Comment by zahraaalizadeh** [comment]
Hi folks, I'm planning to take on this issue. If anyone has specific ideas or suggestions on how to "Google-fy" the 404 page, please feel free to share!

**Comment by andrewpollock** [comment]
My thoughts:

1) Make it match the rest of the OSV.dev website in its presentation (i.e. same CSS)
2) Maybe an outline to the documentation or FAQ
3) Analytics

**Comment by zahraaalizadeh** [comment]
@andrewpollock I think this issue should have resolved.

**Comment by andrewpollock** [comment]
Indeed! Thank you!
