### ISSUE TITLE
Method ranges() Returning List instead of set

### ISSUE THREAD

**Issue by UVvirus** [google/osv.dev#1606]
In Impact.py([here](https://github.com/google/osv.dev/blob/c8d6717fd63ef85ac0c1e0cc551cd1cfcc76a9d9/osv/impact.py)) on [#L79](https://github.com/google/osv.dev/blob/c8d6717fd63ef85ac0c1e0cc551cd1cfcc76a9d9/osv/impact.py#L79) it is mentioned that **"Return a set representing the collected commit ranges."**

But it returns a list ([#L86)](https://github.com/google/osv.dev/blob/c8d6717fd63ef85ac0c1e0cc551cd1cfcc76a9d9/osv/impact.py#L86)

Possible Fix: 
1) **return set(ranges)**   on #L86

### [OR]
2) Change the comment from "**Return a set**" to "**Return a List**"

**Comment by UVvirus** [comment]
can i take this issue?

**Comment by andrewpollock** [comment]
By all means! Please review https://github.com/google/osv.dev#contributing

**Comment by UVvirus** [comment]
The issue has been fixed on this commit. https://github.com/google/osv.dev/commit/3501048dc4a7b8ee26cbba3d79119b7ebc0f9994

Thank you for fixing it. Let me close the issue.

**Comment by UVvirus** [comment]
**FIXED!!!**
