### ISSUE TITLE
"ranges" is used both as a method name and as a variable name

### ISSUE THREAD

**Issue by UVvirus** [google/osv.dev#1607]
In Impact.py, the name **"ranges"** is used both as a method name([#L78](https://github.com/google/osv.dev/blob/c8d6717fd63ef85ac0c1e0cc551cd1cfcc76a9d9/osv/impact.py#L78)) and a variable name([#L80](https://github.com/google/osv.dev/blob/c8d6717fd63ef85ac0c1e0cc551cd1cfcc76a9d9/osv/impact.py#L80)) for a list. This is not recommended because it can lead to confusion and unexpected behavior.

I kindly request you to change the name.

**Comment by karthikmurali60** [comment]
@andrewpollock can I contribute to this issue ?

**Comment by andrewpollock** [comment]
By all means. Please review https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md

**Comment by another-rex** [comment]
Resolved in #1636
