### ISSUE TITLE
Show published date in osv.dev/list

### ISSUE THREAD

**Issue by alex** [google/osv.dev#1608]
Right now only the Last Modified date is shown, however this can be confusing for vulnerabilities originally published years ago. Right now this is the case for (almost?) all of the recent Python vulnerabilities on https://osv.dev/list?ecosystem=PyPI&q=

If published date were listed and we could sort by it, this would make it easier to find new vulnerabilities.

**Comment by oliverchang** [comment]
@another-rex I think you brought up a similar point before.

**Comment by another-rex** [comment]
I've been thinking of replacing the modified date with the published date altogether, and sort by published date, since as you said the modified date is quite confusing.

**Comment by another-rex** [comment]
Fixed in #1632
