### ISSUE TITLE
Bitnami CVE feed

### ISSUE THREAD

**Issue by gongomgra** [google/osv.dev#1630]
Hello team!

We have just found out [this list of pending data sources](https://github.com/google/osv.dev/issues/1438) to be imported and that our [Bitnami CVE feed](https://github.com/bitnami/vulndb) is on the list. Can you tell us if we can be of help with this?

**Comment by oliverchang** [comment]
Hi! Thanks for reaching out. We just never got around to this feed :) 

Ingestion itself is pretty simple for us to do, but to make the ingestion itself useful we typically need version ordering and enumeration support (see e.g. https://github.com/google/osv.dev/commit/d3e242bc856d834c6fe20d1727d0103f5846574e where the R ecosystem was supported).

There is an exception though, if the advisories follow strict SemVer 2.0 for version ranges. These entries can be ingested without any additional version ordering support.

The current BITNAMI entries seem to state the version ranges use SemVer: https://github.com/bitnami/vulndb/blob/main/data/activemq/BIT-2020-11998.json. I just want to clarify that this is explicitly [SemVer 2.0](https://semver.org/) ?

**Comment by oliverchang** [comment]
I also filed https://github.com/bitnami/vulndb/issues/149 to point out a small issue.

**Comment by gongomgra** [comment]
Hi @oliverchang,

Thanks for checking this question. Yes, our version ranges meet the SemVer 2.0 specs. We updated some wrong versions apart from fixing the ecosystem typo as part of [bitnami/vulndb/151](https://github.com/bitnami/vulndb/pull/151). Is there anything else we can help you with? Thanks!

**Comment by andrewpollock** [comment]
Hi,

I've taken the liberty of adding the Bitnami repo to our staging instance's list of sources to validate importing it, and we'll move forward from here. If everything is optimal, I would expect we ought to be able to proceed with adding it to OSV.dev's production instance within the next 2-4 weeks.

**Comment by oliverchang** [comment]
Our test instance has started to ingest this: https://oss-vdb-test.appspot.com/list?ecosystem=&q=Bitnami

**Comment by gongomgra** [comment]
Hi @oliverchang,

Sorry for the delay, and thanks for your message! How is the testing step going? Is there anything else we can help you with?

**Comment by michaelkedar** [comment]
Hi,
Testing went well, so I've just started ingesting this on production: https://osv.dev/list?ecosystem=Bitnami&q=
Sorry for the delay on our end!

**Comment by oliverchang** [comment]
Thanks @michaelkedar!

Also apologies for the delay here and for dropping the ball.

I've also filed two more issues we've noticed with the Bitnami repo:

- https://github.com/bitnami/vulndb/issues/180 (mostly a more aesthetic issue) 
- https://github.com/bitnami/vulndb/issues/181 (potentially more serious as it can hide vulnerable packages). 

Would you be able to take a look?

**Comment by gongomgra** [comment]
Hi @oliverchang,

Thanks for getting back to this. Let me check them.
