### ISSUE TITLE
How should I fully query MAVEN’s vulnerability dependencies?

### ISSUE THREAD

**Issue by FuNianTongXue** [google/osv.dev#1635]
How should I fully query MAVEN's vulnerability dependencies through the API?

**Comment by hayleycd** [comment]
Hello @FuNianTongXue! Thanks for your question. 

It is currently not possible to query our API for all Maven vulnerabilities. 

However, you can find all of the Maven vulnerabilities [on our website](https://osv.dev/list?ecosystem=Maven&q=) or you can download a zip file of all the Maven vulnerabilities [here](https://osv-vulnerabilities.storage.googleapis.com/Maven/all.zip). You can find more info about the bulk download [here](https://google.github.io/osv.dev/data/#data-dumps). 

@oliverchang @andrewpollock Is this something we should offer in the future? Is this kind of API call possible, but just under documented?

**Comment by FuNianTongXue** [comment]
Do we have any .net related vulnerabilities?

**Comment by hayleycd** [comment]
Yes, you can find them [here](https://osv.dev/list?ecosystem=NuGet&q=). 

You can see all of our ecosystems [here](https://osv.dev/list).

**Comment by oliverchang** [comment]
Closing as it appears the question has been answered.
