### ISSUE TITLE
Minor issues with Debian advisories revisited

### ISSUE THREAD

**Issue by rhalar** [google/osv.dev#1698]
This is directly related to the previous issue
https://github.com/google/osv.dev/issues/1525

This time `<unfixed>` versions seemed to be present, and I am unsure if this is expected. Perhaps just omitting the fixed version would be preferable?  
https://osv.dev/vulnerability/DSA-746-1
https://osv.dev/vulnerability/DSA-866-1
https://osv.dev/vulnerability/DSA-880-1

**Comment by oliverchang** [comment]
@another-rex can you take a look here?

**Comment by rhalar** [comment]
@another-rex These seem to be present in the current dataset though

**Comment by oliverchang** [comment]
> @another-rex These seem to be present in the current dataset though

I believe this will be pushed as part of our next release this week. @another-rex please correct me if I'm wrong.

**Comment by another-rex** [comment]
Yep, it should be fixed in the next release (some time this week), I'll add an additional comment here when the release is out.

**Comment by another-rex** [comment]
Fixed now on osv.dev!
