### ISSUE TITLE
osv.dev  search by Repo URL

### ISSUE THREAD

**Issue by another-rex** [google/osv.dev#1722]
**Is your feature request related to a problem? Please describe.**
It's confusing / frustrating that you can't search by repo URL, especially for ecosystemless adivisories, which the only way to identify the package, is by repo URL. It also shows up under Packages in the vulnerability list, so allowing search keeps it consistent.

![image](https://github.com/google/osv.dev/assets/106129829/64e849f7-8711-4f7c-bf75-cb37dd1542da)

**Describe the solution you'd like**
Search indices should be also populated by repo URL (with and without scheme, and maybe each segment in the repo URL?). 

E.g. for repourl `https://github.com/MariaDB/server`
search_indicies should also have `https://github.com/MariaDB/server`, `github.com/MariaDB/server`, `MariaDB`, `server`

**Comment by andrewpollock** [comment]
@aidoskanapyanov this one may be challenging to work on without an instance of OSV.dev running on GCP, so it may not be the best first issue for an external contributor. Feel free to sample the others, or if you want to try and spin up an instance of OSV.dev on your own GCP project, that would be a good test of the ability for an external contributor to do so...
