### ISSUE TITLE
GHSA-cr45-98w9-gwqx: breaks OSV format 

### ISSUE THREAD

**Issue by akuleshov7** [google/osv.dev#1740]
https://osv.dev/vulnerability/GHSA-cr45-98w9-gwqx

Vulnerability has broken format:
```
  "severity": [
    {
      "type": "CVSS_V3",
      "score": ""
    }
  ],
```

It looks like `type` is provided, `score` is provided (empty string). But actually `score` is not provided (it is empty). OSV should prohibit such stubs, as it has no sense and definitely reporter's issue. Reporter should not submit `severity` at all or submit a real value.

**Comment by nulls** [comment]
Actually, provided format doesn't break the schema (but anyway it's invalid).

But the JSON file https://osv-vulnerabilities.storage.googleapis.com/PyPI/GHSA-cr45-98w9-gwqx.json missed the score field:

```json
  "severity": [
    {
      "type": "CVSS_V3"
    }
```
But JSON on github (https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-cr45-98w9-gwqx/GHSA-cr45-98w9-gwqx.json) does: 
```json
  "severity": [
    {
      "type": "CVSS_V3",
      "score": ""
    }
  ],
```

**Comment by oliverchang** [comment]
Hi! Can you please raise this issue with GitHub at https://github.com/github/advisory-database/issues to exclude the severity completely when it's empty? 

OSV.dev does have slightly different handling of empty fields for the entries it ingests, but as mentioned it's not valid to provide empty severities in the first place.

**Comment by nulls** [comment]
> Hi! Can you please raise this issue with GitHub at https://github.com/github/advisory-database/issues to exclude the severity completely when it's empty?
> 
> OSV.dev does have slightly different handling of empty fields for the entries it ingests, but as mentioned it's not valid to provide empty severities in the first place.

raised: https://github.com/github/advisory-database/issues/2885

**Comment by oliverchang** [comment]
I'll close the issue on our end, since this is a problem with the source (and I'm not sure what we can do here).
