### ISSUE TITLE
Searching for a vuln ID with leading whitespace returns no results

### ISSUE THREAD

**Issue by maxfisher-g** [google/osv.dev#1755]
**Describe the bug**
When I paste a valid vuln ID into the search bar and (accidentally) include some leading whitespace, I would like to see the results for the vuln ID. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to (https://osv.dev/list)
2. Click on the search bar and paste, e.g. " GO-2022-0646"
3. Click search
4. See no results

**Expected behaviour**
The same results as if I had entered "GO-2022-0646" (i.e. no leading whitespace)

**Additional context**
This would improve the user experience

**Comment by mustafaazad03** [comment]
Hi @maxfisher-g @hogo6002 @andrewpollock , 
I want to work on this issue, can I take this issue??

**Comment by andrewpollock** [comment]
@mustafaazad03 sure can!
