### ISSUE TITLE
Inconsistent Ecosystem Handling in OSV Query API for Vulnerability and Malware Reports

### ISSUE THREAD

**Issue by abhisek** [google/osv.dev#1759]
**Describe the bug**

The OSV query API works by taking `ecosystem`, `name` and `version` as input as documented [here](https://google.github.io/osv.dev/post-v1-query/). This works for querying vulnerabilities. However with the `ecosystem` input set, OSV API do not report any malicious indicators that may be available for the package. OSV API however reports malicious indicators if the `ecosystem` input parameter is skipped.

**To Reproduce**

The following query correctly returns the malicious indicators associated with the package `z-dsm` in `npm` ecosystem

```bash
curl -d \
  '{"package": {"name": "z-dsm"}, "version": "1.0.1"}' \
  "https://api.osv.dev/v1/query"
```

However when `ecosystem` is added in the above query, it does not return any result

```bash
curl -d \
  '{"package": {"name": "z-dsm", "ecosystem": "npm"}, "version": "1.0.1"}' \
  "https://api.osv.dev/v1/query"
```

**Expected behaviour**

The OSV API should be consistent for both vulnerabilities and malware reports since they use the same API and response schema. For example, a query such as below should respond with all vulnerabilities and malicious indicators

```
curl -d \
  '{"package": {"name": "z-dsm", "ecosystem": "npm"}, "version": "1.0.1"}' \
  "https://api.osv.dev/v1/query"
```

**Comment by oliverchang** [comment]
Thanks for the report! It looks like we're not handling SemVer eccosystems properly when exact versions are specified. 

The issue is here:

https://github.com/google/osv.dev/blob/4ef0664dc07dae1834dc16fe9267c9c73ac84716/gcp/api/server.py#L838

We're not matching on exact versions the way we do them here: 

https://github.com/google/osv.dev/blob/4ef0664dc07dae1834dc16fe9267c9c73ac84716/gcp/api/server.py#L750

https://github.com/google/osv.dev/blob/4ef0664dc07dae1834dc16fe9267c9c73ac84716/gcp/api/server.py#L764

**Comment by oliverchang** [comment]
@cuixq wanna give a stab at fixing this?

**Comment by abhisek** [comment]
Awesome. That was super fast. Thanks for resolving this @oliverchang @cuixq

**Comment by oliverchang** [comment]
> Commit [ossf/malicious-packages@17c7476](https://github.com/ossf/malicious-packages/commit/17c7476d86887fd8362390acdb6791aeb0b293c1) seems fixes this issue.
> 
> ```
> {"package": {"name": "z-dsm", "ecosystem": "npm"}, "version": "1.0.1"}
> ```
> 
> now also returns the malicious indicators.
> 
> however,
> 
> ```
> {"package": {"name": "z-dsm"}, "version": "1.0.1"}
> ```
> 
> now returns `MAL-2023-8393` two times - we should dedupe the result to resolve this.

Thanks @cuixq ! I think there's still the underlying problem of us not querying the exact versions in the semver case though, as @michaelkedar says in https://github.com/google/osv.dev/pull/1779#pullrequestreview-1709393170

**Comment by cuixq** [comment]
yes - I am working on a commit resolving this!
