### ISSUE TITLE
Indexer: don't index third party dependencies. 

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#1766]
https://github.com/gemini-testing/png-img seems to cause matches against it instead of libpng.

**Comment by oliverchang** [comment]
(from https://github.com/google/osv-scanner/pull/621)

**Comment by another-rex** [comment]
Hmm... there's probably a more general approach here where we ignore these "third_party" and similar folders from the initial indexing, could reduce a lot of false positives. 

Also detecting a non C/C++ package manifest file and avoiding these repositories when indexing will help.

**Comment by oliverchang** [comment]
> Hmm... there's probably a more general approach here where we ignore these "third_party" and similar folders from the initial indexing, could reduce a lot of false positives.

+1 that's a great idea! In the meantime though, does it seem reasonable ot just remove the config for this repo and delete all relevant index entities?

**Comment by another-rex** [comment]
Yep can do

**Comment by another-rex** [comment]
png-img has now been removed from the indexer config and datastore hashes.
