### ISSUE TITLE
Osv.dev fails to build

### ISSUE THREAD

**Issue by madberries** [google/osv.dev#1767]
I followed the steps listed under `docs/README.md` and I am unable to build this repository.

**To Reproduce**
1. ```bash
   git clone --recursive https://github.com/google/osv.dev.git
    ```
2. ```bash
   cd osv.dev
   git submodule update --init --recursive
   ```
3. ```bash
   go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
   ```
When running step 3, I get the following error:
```bash
$ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest: module github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2: Get "https://proxy.golang.org/github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/@v/list": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:38289->[::1]:53: read: connection refused
```
It seems that I also get similar connection issues when running `go mod download`.

I am running on Arch Linux and go version: `go version go1.21.3 linux/amd64`

**Comment by andrewpollock** [comment]
I think this may be a local networking issue. I tried it from my `Cloud Shell`:

```
$ go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.18.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading google.golang.org/protobuf v1.31.0
go: downloading google.golang.org/grpc v1.58.0
go: downloading github.com/golang/glog v1.1.0
go: downloading golang.org/x/text v0.13.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20230822172742-b8732ec3820d
go: downloading google.golang.org/genproto v0.0.0-20230803162519-f966b187b2e5
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230822172742-b8732ec3820d
```

See:

* https://sum.golang.org/
* https://go.dev/ref/mod#private-module-privacy

for further details on how to not use the Go proxy if you're in an environment that has outbound network ACLs or other connectivity issues preventing you from using it.
