### ISSUE TITLE
Data quality issue with GHSA-pc5p-h8pf-mvwp

### ISSUE THREAD

**Issue by Michal-Kubricht** [google/osv.dev#1774]
**The CVE ID**
https://osv.dev/vulnerability/GHSA-pc5p-h8pf-mvwp
https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2020/04/GHSA-pc5p-h8pf-mvwp/GHSA-pc5p-h8pf-mvwp.json

**Describe the data quality issue observed**
Severity score value contains a typo and is corrupted for parsing with CVSSv3. The value "CVSS:3.1/AV:A/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N/" contains additional "/" at the end.

**Suggested changes to record**
Just remove trailing "/" and have "CVSS:3.1/AV:A/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N"

**Comment by oliverchang** [comment]
Hi! Thanks for the report.

Can you please report this to the upstream github advisory-database repo? OSV.dev is an aggregator, and there's not much we can do to fix this ourselves :)

**Comment by Michal-Kubricht** [comment]
Thank you for pointing this out that there is another repo 👍

**Comment by andrewpollock** [comment]
Hi @Michal-Kubricht 

We recently added some sign posting to the OSV.dev web interface to make it clearer where the source of a given record is (for a subset of our data sources), see:

![image](https://github.com/google/osv.dev/assets/6906046/a0584ad0-e8ad-4e4c-9a1a-880ca0d8feb4)

If you have any feedback on how we can make this clearer, we'd be most appreciative.
