### ISSUE TITLE
Mobile View : Columns in list are not fully visible

### ISSUE THREAD

**Issue by mustafaazad03** [google/osv.dev#1803]
**Is your feature request related to a problem? Please describe.**
In Mobile View, when you go to [https://osv.dev/list](https://osv.dev/list) only 2 fields are visible which is not appropriate for users who view in mobile.
![image](https://github.com/google/osv.dev/assets/97380192/f875ac61-2a76-4ce1-a9c7-432fd55c6bd0)

**Describe the solution you'd like**
As a solution, I am thinking of making the columns scrollable horizontally which is more convenient for the user to see other fields.

**Describe alternatives you've considered**
In the alternative, we can put a dropdown where users can access different fields to access data.

**Comment by mustafaazad03** [comment]
I want to work on this !!

**Comment by andrewpollock** [comment]
@mustafaazad03 go for it!

**Comment by mustafaazad03** [comment]
Thank you @andrewpollock, I will resolve this soon!

**Comment by andrewpollock** [comment]
Happy New Year @mustafaazad03 I thought I'd check in and see how you're going with this?

**Comment by mustafaazad03** [comment]
Happy New Year @andrewpollock, Sorry for this late response from my side, I am working on it. will let you know about this soon. 
Thank you for reminding me

**Comment by mustafaazad03** [comment]
https://github.com/google/osv.dev/assets/97380192/2521323f-1437-455b-b362-28b649051923

Is this solution is works ?

**Comment by another-rex** [comment]
Thanks! Can you put the table in it's own scrollable div (so that the search box/header stays locked horizontally)? I think that'll look neater.

**Comment by another-rex** [comment]
This was fixed in #1962
