### ISSUE TITLE
Duplicated entries coming from Bitnami CVE renaming

### ISSUE THREAD

**Issue by carrodher** [google/osv.dev#1859]
👋 Bitnami team member here!
We recently found that the number of CVEs reported by the [OSV integration](https://osv.dev) has multiplied by two abruptly. We are currently on 6K vulnerabilities while in the past month, we were on 3K. 

After taking a look at what may be happening, it seems that this unexpected growth was caused by the actions taken to solve this issue (https://github.com/bitnami/vulndb/issues/181) reported by @oliverchang.

In summary, after the changes implemented to solve the mentioned issue, we renamed the CVE files from `BIT-` to `BIT-asset-`, see https://github.com/bitnami/vulndb/pull/212. The problem nowadays is that the [OSV integration](https://osv.dev) is showing both, the old and the new format, for instance:
- Old: https://osv.dev/vulnerability/BIT-2023-44487
- New: https://osv.dev/vulnerability/BIT-tomcat-2023-44487

We've downloaded a copy of the data dump from OSV dev from [here](https://storage.googleapis.com/osv-vulnerabilities/index.html?prefix=Bitnami/), so now we can get precise stats:

```console
$ wget https://www.googleapis.com/download/storage/v1/b/osv-vulnerabilities/o/Bitnami%2Fall.zip?generation=1701771181987732&alt=media
$ unzip Bitnami_all.zip

# NUMBER OF OLD BIT- ENTRIES (ALIASES)
$ find .  -regex ".*BIT-[0-9].*json" | wc -l
    3305

# NUMBER OF NEW BIT-ASSET ENTRIES
$ find .  -regex ".*BIT-[a-z].*json" | wc -l
    3615

# TOTAL NUMBER OF ENTRIES IN OSV DUMP
$ find .  -regex ".*BIT-.*json" | wc -l
    6920
```

According to this background and context, `BIT-` entries are NOT expected anymore. Is there a way to not ingest them? Thanks!

**Comment by another-rex** [comment]
I removed the old entries now, in < 24 hours the number should reflect the correct values, and the exported data should be  updated as well.

**Comment by carrodher** [comment]
Thanks for the prompt response!
