### ISSUE TITLE
Usage question for OSV

### ISSUE THREAD

**Issue by rpau** [google/osv.dev#1884]
Hi,

Thanks for this amazing project. We are evaluating different solutions to scan OSS dependencies and include the results in a commercial product. By reading the documentation looks like there is no constraint but it is unclear to me. Could you clarify what usages are not allowed?

**Comment by hayleycd** [comment]
Hi @rpau I can't answer your question fully, but a good place to start is to take a look at our [license](https://github.com/google/osv.dev/blob/master/LICENSE). 

@oliverchang should be able to answer further questions.

**Comment by rpau** [comment]
Thanks, yes. We read that license, and looks like we can use it, but I would like to properly confirm because of the split of the API from the database.

**Comment by oliverchang** [comment]
Hi! Sorry for the late reply. 

OSV.dev (and OSV-Scanner) is fully open source and under the Apache 2.0 license. There should be no restrictions at all for use in commercial products.

**Comment by rpau** [comment]
Thanks!
