### ISSUE TITLE
Question about heuristics used to detect vulnerable commits from git range

### ISSUE THREAD

**Issue by RomainLefeuvre** [google/osv.dev#1897]
Hello,
For a research study, I'm interested in the algorithm/heuristics used in OSV to determine whether a commit is vulnerable or not. 

The OSSF osv-schema outlines the different type of range, the GIT type is one of them. The specification do not mention sufficient details to obtain a similar behaviour that the one implemented in osv.dev.

Impact.py seems to contain the code that populate the "cloud datastore" that contains all the vulnerable commit associated to a vulnerability object.

Impact.py provide heuristics made on git patches [https://github.com/google/osv.dev/blob/02af8ac455cec0502a62bd22b86ce9bbe59cb51e/osv/impact.py#L160](https://github.com/google/osv.dev/blob/02af8ac455cec0502a62bd22b86ce9bbe59cb51e/osv/impact.py#L160) , while the documentation only mention an evaluation algorithm that is based on a version comparison operator ( implying for GIT type to reason on parent relation between commits)

Thus, the specification mention only the following information :

* It defines a comparison operator for each range type, here for GIT type: 

> _The relation u < v is true when commit u is a (perhaps distant) parent of commit v_

*   It defines the algorithm based on the comparison operator, thus agnostic of the GIT type 

```text-plain
func IncludedInRanges(v, ranges)
  for range in ranges
    if BeforeLimits(v, range)
      vulnerable = false
      for evt in sorted(range.events)
        if evt.introduced is present && v >= evt.introduced
           vulnerable = true
        else if evt.fixed is present && v >= evt.fixed
           vulnerable = false
        else if evt.last_affected is present && v > evt.last_affected
           vulnerable = false

      if vulnerable
        return true

  return false
```

Is there any plan to integrate the evaluation algorithm related to GIT ranges in the specification ? There is no mention of use of  “equivalent commit” i.e git patch id, neither in the relation definition nor in the evaluation algorithm.

For instance we can propose something like that   :

```text-plain
func IncludedInRanges(v, ranges)
  for range in ranges
    if BeforeLimits(v, range)
      vulnerable = false
      events = addEquivalentEvent(range)
      for evt in sorted(events)
        if evt.introduced is present && v >= evt.introduced
           vulnerable = true
        else if evt.fixed is present && v >= evt.fixed
           vulnerable = false 
        else if evt.last_affected is present && v > evt.last_affected
           vulnerable = false

      if vulnerable
        return true

  return false
  
 func addEquivalentEvent(range)
    eventsWithEquivalent = []
    for evt in range.events
        eventsWithEquivalent.add(evt)
    	//If the event is a last_affected event, no equivalent search
    	if evt.last_affected is present
    		continue
		else
			eventsWithEquivalent.addAll(getEquivalentEvents(evt,range.repo))    
	return eventsWithEquivalent
   	
```

It would be really helpful to add the heuristic related to GIT range type in the evaluation algorithm of the OSV spec. 

There are some other, part of the implementation that are not clear for me and that prevent me to reproduce on my side your heuristic (I will create other issues) .

Is there any way to access the database where the result of impact.py is saved ? I did not find any way to obtain the database of all the vulnerable commits (and their associated vulnerability) without re-executing the extraction manually of all commits from range, on the source of all repositories.

Thanks,

Sincerely 
Romain LEFEUVRE

**Comment by oliverchang** [comment]
Hello, 

If I'm understanding your questions correctly, I believe  https://github.com/google/osv.dev/issues/1898#issuecomment-1884071754 and https://github.com/ossf/osv-schema/issues/216 attempts to cover them. 

Please let me know if you still have questions.

**Comment by RomainLefeuvre** [comment]
Hello,
Thanks again for your response ! 

Yes https://github.com/ossf/osv-schema/issues/216 cover my question. I also agree with @zacchiro in the sense that the `cherry pick ` case might be integrated into the OSV spec. 

>Is there any way to access the database where the result of impact.py is saved ? I did not find any way to obtain the database of all the vulnerable commits (and their associated vulnerability) without re-executing the extraction manually of all commits from range, on the source of all repositories.

Do you have any plan to create an API to allow read access in your internal database?  I'm looking for a way to access the list of all vulnerable commit of all the affected package of a given vulnerability.

Sincerly,
Romain Lefeuvre

**Comment by andrewpollock** [comment]
Hi @RomainLefeuvre 

> Do you have any plan to create an API to allow read access in your internal database? I'm looking for a way to access the list of all vulnerable commit of all the affected package of a given vulnerability.

At this time, we have no plans to create an API to allow such internal database access (this is due to resourcing constraints to produce and maintain such an API).

There are also no plans to publicly export these commits to GCS (this is due to the volume of data that would need to be exported).
