### ISSUE TITLE
Need some help understanding how to tell which dependency is newer

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#1948]
Followed https://ossf.github.io/osv-schema/#evaluation to implement the algorithm in Java.

For well-structured semver versions, it works fine.

But what about something like this?:

2.6.7
2.6.7.1
2.6.7.2
2.6.7.3
2.6.7.4
2.6.7.5
2.6.7.RELEASE

Which of those is the newest version?

Similar questions for this:
24.0.0
24.0.0.Beta1
24.0.0.Final
24.0.0.SP1

and this:

24.0.1
24.0.1.Final

and this:
4.1
4.1-BETA-1
4.1-alpha1
4.1-alpha2
4.1-beta1
4.1-milestone-1
4.1-milestone-2
4.1-rc-1
4.1-rc1
4.1-rc6

and etc.

**Comment by jimshowalter** [comment]
semver_index.py

**Comment by andrewpollock** [comment]
Hi @jimshowalter it looks like you've managed to answer this yourself, but I'm always interested to know if there's an opportunity for improving our documentation, or the discoverability of the answer. Got any actionable feedback on that front?

**Comment by oliverchang** [comment]
Adding onto @andrewpollock 's comment here: 

semver_index.py is used only for strict SemVer schemes. In general every ecosystem tends to have their own version ordering rules, which we implement here: https://github.com/google/osv.dev/tree/master/osv/ecosystems
