### ISSUE TITLE
Misnamed and probably pointless function

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#1954]
**Describe the bug**

In semver_index.py._coerce_suffix, there's this code:

    for component in match.group(1)[1:].split('.'):
      if not component:
        pre_components.append('-')
      elif component.isdigit():
        pre_components.append(_remove_leading_zero(component))

The components are split on '.', so no component can contain a '.'.

Yet _remove_leading_zero's job is removing leading '.'s:

```
def _remove_leading_zero(component):
  """Remove leading zeros from a component."""
  if component[0] == '.':
    return '.' + str(int(component[1:]))
  return str(int(component))
```

The function is misnamed, because it has nothing to do with zeroes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Look at the code.

**Expected behaviour**
1. The function name should be changed to _remove_leading_period.
2. The function probably should be deleted because it has no effect.

**Comment by andrewpollock** [comment]
@cuixq FYI: Keep this in mind when reviewing code for readability
