### ISSUE TITLE
Exact versions are missing from some OSV .json vuln files

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#1960]
**Describe the bug**

In https://github.com/google/osv.dev/issues/1953, another-rex said: "We also do not support generic range matching for non-semver ecosystems, but _**we do enumerate through all published versions of the package and index them to do exact matching**_."

That would be super-helpful, because then versions could be compared using simple lookups in the versions[] arrays.

Unfortunately it turns out there are more than 1,000 vuln files that have empty versions[] arrays, and only have ranges.

For example, GHSA-4j38-wjhf-884r.json.

Did I misunderstand what another-rex was saying?

If OSV has the ability to expand ranges into exhaustive version lists, could the lists be added to all of the vuln files? It would make things so much easier.

**To Reproduce**

Steps to reproduce the behaviour:
1. grep the .json files in https://storage.googleapis.com/osv-vulnerabilities/index.html?prefix=Maven/ for "versions": [].

**Expected behaviour**

Ideally there would be no empty versions[] arrays, and the contents of the arrays would be the expanded form of all of the ranges.

**Comment by jimshowalter** [comment]
What we were trying to do is write a custom Gradle plugin that gets data from two sources, Gradle's dependencies task, and all.zip, matches the versions, and reports vulnerabilities.

Matching the versions has turned out to be way too complicated, so we'll call the OSV API instead. We were trying to avoid that because we have a lot of dependencies.

You're using maven.py and helper_base._deps_dev_enumerate to get a sorted list of all affected versions. You could do that ahead of time, and put the result in the versions[] arrays. Then it would be trivial to tell if a version is affected.

**Comment by andrewpollock** [comment]
Hi @jimshowalter thanks for surfacing this. In the case of [GHSA-4j38-wjhf-884r](https://osv.dev/vulnerability/GHSA-4j38-wjhf-884r), looking at the [source data](https://deps.dev/maven/org.richfaces%3Arichfaces-core/4.5.17.Final/versions) [used for Maven](https://github.com/google/osv.dev/blob/f853bc9845f76620ec94f3662bf522fea0368a5b/osv/ecosystems/maven.py#L241), there are no versions (any more?) within the affected range, so an empty `affected.versions[]` array seems appropriate (and correct) under the circumstances.

From a usability perspective, what would you have found most useful here? Our first thought was an [FAQ](https://google.github.io/osv.dev/faq/) entry, given this is OSV.dev version enumeration behaviour. Another potential callout *might* be in the [OSV Schema documentation](https://ossf.github.io/osv-schema/#affectedversions-field) (/cc @oliverchang for his thoughts)

This has raised (currently unanswered questions) of:
- surfacing enumeration failure versus (correctly) failing to enumerate any versions
- inconsistent output between OSV.dev's API and OSV.dev's exports, with respect to empty `affected.versions[]` field treatment.

**Comment by jimshowalter** [comment]
Interesting! Somewhere, a paragraph with this content, but wordsmithed however works best, could be published. Maybe where ecosystems are discussed?:

We do not support generic range matching for non-semver ecosystems, but we do enumerate through all published versions of the package and index them to do exact matching. In some cases it turns out there are no applicable versions, so the versions array is empty. Note that there is no reason to look at ranges for non-semver ecosystems, because everything in them is also in the versions arrays.

**Comment by andrewpollock** [comment]
> Maybe where ecosystems are discussed?

I'm interpreting this as in https://ossf.github.io/osv-schema/#affectedpackage-field somewhere. I'm more hesitant to add something to the OSV Schema documentation, because this really relates to OSV.dev version enumeration behaviour than the schema itself

I think there's an opportunity to enhance the OSV Schema documentation https://ossf.github.io/osv-schema/#affectedversions-field section and https://ossf.github.io/osv-schema/#affectedrangesevents-fields to discuss when a record consumer could or should utilise `affected.versions[]` versus figuring out the versions in `affected[].ranges[].events` for themselves.

While we wait for @oliverchang to opine on that, I'll go ahead with an osv.dev FAQ entry...

**Comment by jimshowalter** [comment]
Thank you!
