### ISSUE TITLE
Databases have not been updated since Thu, 08 Feb 2024

### ISSUE THREAD

**Issue by G-Rath** [google/osv.dev#1981]
Both https://osv.dev/vulnerability/GHSA-7c6p-848j-wh5h and https://osv.dev/vulnerability/GHSA-78xj-cgh5-2h22 seem to be missing at least:

```
❯ curl-headers-only -X HEAD https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip
HTTP/2 200
x-guploader-uploadid: ABPtcPrro9PtEfrhYe4g3epdcrFFDNAAc_bHOc1-VEloFtbACuWQaD574NYZlzWD-zLqtA2I0A
expires: Sun, 11 Feb 2024 23:04:56 GMT
date: Sun, 11 Feb 2024 22:04:56 GMT
cache-control: public, max-age=3600
last-modified: Thu, 08 Feb 2024 05:33:19 GMT
etag: "d3743abfc43d21b9acdc60183ba1724e"
x-goog-generation: 1707370399249870
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 12941961
content-type: application/zip
x-goog-hash: crc32c=mEFk+A==
x-goog-hash: md5=03Q6v8Q9Ibms3GAYO6FyTg==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 12941961
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

curl: (18) transfer closed with 12941961 bytes remaining to read
```

Note that `last-modified` header:

> last-modified: Thu, 08 Feb 2024 05:33:19 GMT

**Comment by jimshowalter** [comment]
I was just about to file an issue for the same reason. The .json files contain this, but the API does not return it:

`>         "id": "GHSA-57m8-f3v5-hm5m",
>         "summary": "Withdrawn Advisory: Netty-handler does not validate host names by default",
>         "severity": "MODERATE",
>         "cves": [
>           "unknown CVE ID, but artifact has vulns"
>         ]
>       },`

**Comment by oliverchang** [comment]
This issue should be resolved now. We are just keeping this open to track any work we can do to prevent this happening again in the future. 

Re @jimshowalter 's question
> I was just about to file an issue for the same reason. The .json files contain this, but the API does not return it:

The API does return this at https://api.osv.dev/v1/vulns/GHSA-57m8-f3v5-hm5m. Are you referring to this being returned from `/v1/query` or `/v1/querybatch`? Because this vulnerability is marked as withdrawn, this won't be returned by those endpoints as they're treated as not existing in that context.

**Comment by jimshowalter** [comment]
When calling the API, not returned. When reading from the out-of-date .json files, was present. Now it's probably gone from the .json files too.

**Comment by oliverchang** [comment]
@jimshowalter Could you please clarify which API endpoint you're referring to? The advisory in question is returned by the API at https://api.osv.dev/v1/vulns/GHSA-57m8-f3v5-hm5m, but it will not be returned by our other query endpoints because it's marked as "withdrawn".

**Comment by jimshowalter** [comment]
/v1/querybatch

When we called that, it didn't return the withdrawn advisory. When we ran against the downloaded .json files in Maven all.zip, they were present.

**Comment by oliverchang** [comment]
Thanks. That's intended behaviour, as withdrawn advisories should be treated as non-existent for the purpose of matching vulnerabilities to package versions (which is what the query endpoints do).

**Comment by jimshowalter** [comment]
Ah. That means just matching versions in the .json files isn't going to work.

**Comment by jimshowalter** [comment]
If they're withdrawn, why are they included in the .json files at all?

**Comment by oliverchang** [comment]
> If they're withdrawn, why are they included in the .json files at all?

These are included for historical reasons. It should be very easy to distinguish these: They have a  top level "withdrawn" field.

**Comment by jimshowalter** [comment]
Ack.

**Comment by oliverchang** [comment]
Closing this in favour of #1990.
