### ISSUE TITLE
Is there something better to use than last-modified when determining whether to redownload the all zip?

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#1993]
**Is your feature request related to a problem? Please describe.**

We download the Maven-all.zip, unzip it, and match dependencies to vulns.

In order to make sure we're current, we call head on the zip first, and compare last-modified to a file, saved the previous time we downloaded the zip, that contains the previous last-modified (and if there is no such file, we do the initial download).

Unfortunately, last-modified seems to change once an hour, and yet when we unzip and compare to the previous contents, often nothing has changed.

We can't use size info because it changes somehow, even though the contents haven't changed.

The available fields in head are:

x-guploader-uploadid: ABPtcPpXXBXsd5ctGlbi3eURZuo-XTgoPRoPGHgv2YTIw2vwyg6F4eBuX4FzrxhMwMen2wJHc1bJJnq-DA
x-goog-generation: 1708026318109754
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 6444072
x-goog-hash: crc32c=SkCpMA==
x-goog-hash: md5=A417294/XUvR65kzO7geNQ==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 6444072
server: UploadServer
date: Thu, 15 Feb 2024 19:49:19 GMT
expires: Thu, 15 Feb 2024 20:49:19 GMT
cache-control: public, max-age=3600
last-modified: Thu, 15 Feb 2024 19:45:18 GMT
etag: "038d7bdbde3f5d4bd1eb99333bb81e35"
content-type: application/zip
age: 2170
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

**Describe the solution you'd like**

Some field in head that can be relied on to change only when there is a change to the contents of the zip that is meaningful (for example, adding a vuln, retiring a vuln, adding a CVE to a vuln, etc.)

**Comment by andrewpollock** [comment]
Unfortunately our exporter is currently fairly naive, and performs a full reexport on every run, irrespective.

The desire to minimise bandwidth costs is entirely reasonable, and will require some reworking of the export process.

Contributions are, of course very welcome, and depending on your sense of urgency, you may wish to pursue that avenue. If you'd like to have an interactive conversation about how to proceed, we can set something up.

**Comment by another-rex** [comment]
This feature will also help optimise OSV-Scanner's offline/localdb scanning capabilities.

**Comment by andrewpollock** [comment]
> If it re-exports every time, but there are no changes, wouldn't you expect the content length to stay the same?

I haven't exhaustively examined the situation. Possible reasons could be metadata on the files in the zip are changing?

**Comment by jimshowalter** [comment]
Could be. I've updated our plugin to save the previous unzipped dir and compare them. Probably have info tomorrow.

**Comment by andrewpollock** [comment]
I was perusing the exporter source, and it's writing the out the records locally and then zipping them up, so the main source of churn in the zip file is going to be file modification time.

Based on https://simonhearne.com/2022/caching-header-best-practices/ I think at a minimum we'd need to keep the modification time of the zip file stable, and ideally use an etag.

**Comment by jimshowalter** [comment]
Today I have data.

Mostly the only changes in the zip were indeed modification times:

diff -r build/maven-vulns-from-remote-zip/GHSA-223m-pgcq-f3xg.json build/previous-maven-vulns-from-remote-zip/GHSA-223m-pgcq-f3xg.json
8c8
<   "modified": "2024-02-16T08:19:06.995696Z",
---
>   "modified": "2023-11-09T05:31:09.319094Z",
...

However, there were also actual diffs, for example:

diff -r build/maven-vulns-from-remote-zip/GHSA-27xj-rqx5-2255.json build/previous-maven-vulns-from-remote-zip/GHSA-27xj-rqx5-2255.json
12,14c12
<     "cwe_ids": [
<       "CWE-502"
<     ],
---
>     "github_reviewed_at": "2020-04-23T19:32:22Z",
17c15,17
<     "github_reviewed_at": "2020-04-23T19:32:22Z"
---
>     "cwe_ids": [
>       "CWE-502"
>     ]
46c46
<       "url": "https://security.netapp.com/advisory/ntap-20200511-0004"
---
>       "url": "https://security.netapp.com/advisory/ntap-20200511-0004/"

and:

<       "url": "https://security.netapp.com/advisory/ntap-20190619-0001"
---
>       "url": "https://security.netapp.com/advisory/ntap-20190619-0001/"

and others.

I'll run it again in a couple of hours.

**Comment by jimshowalter** [comment]
Ran it again and there were more diffs, not just between modified dates. So this is a red herring--the zip's contents are actually changing.
