### ISSUE TITLE
Missing aliases in some OSV records

### ISSUE THREAD

**Issue by sharonbz** [google/osv.dev#2054]
**Describe the bug**
Some CVEs from the GO vulnerability db are missing the "aliases" tag in the OSV json files: GO-2022-0586, GO-2021-0097

**To Reproduce**
1. curl "api.osv.dev/v1/vulns/GO-2021-0097" - missing "aliases" while https://vuln.go.dev/ID/GO-2021-0097.json has it

**Expected behaviour**
The OSV records should have the aliases

**Screenshots**

**Additional context**

**Comment by oliverchang** [comment]
@hogo6002 , could you please take a look at this?

**Comment by hogo6002** [comment]
> @hogo6002 , could you please take a look at this?

Sure, I will have a look

**Comment by hogo6002** [comment]
`GO-2021-0097` has 8 aliases which is over our [limit (5)](https://github.com/google/osv.dev/blob/f532637d69ac886df1fcf7b2e31f90b19df6f351/docker/alias/alias_computation.py#L25). I can add this vuln into our allow list to bypass the check, or we can increase the `VULN_ALIASES_LIMIT`.

**Comment by sharonbz** [comment]
Hey @hogo6002, thanks for addressing this issue! Just adding a clarification - there are 2 GO-Ids that are passing this limit (both have 8 aliases) hence missing the aliases section:
* GO-2022-0586
* GO-2021-0097
Thanks!

**Comment by hogo6002** [comment]
> * GO-2022-0586
> * GO-2021-0097

Hey @sharonbz, I've added them to the allowList and their aliases are now visible on osv.dev.
Thanks for reporting this issue!
