### ISSUE TITLE
Parity mismatch between API and zip

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#2059]
**Describe the bug**
In our parity test, the assert fails because what's returned from the API doesn't match what we hardcoded to expect.

Which normally would be fine--we'd just update what to expect.

Except when we do that, then the assert fails because what's in the zip doesn't match what we hardcoded to expect.

**To Reproduce**
Get vulns for org.bouncycastle:bcprov-jdk15on:1.57 from both the API and the zip and compare.

**Expected behaviour**
They should match.

**Screenshots**
![api](https://github.com/google/osv.dev/assets/211780/b12cdba2-592d-44d0-ae5b-f7d532c62616)
![zip](https://github.com/google/osv.dev/assets/211780/8661a60f-0546-4f86-aa1e-d6a922a67ced)

**Comment by michaelkedar** [comment]
Just to confirm, the 'Actual' in your first screenshot is from the OSV API, and the 'Actual' in the second is from the zip / bucket download?

Looking at a few of the records in the zip right now, it looks like they should match the API responses.

I suspect you might be detecting the changes on the API side before the data is finished exporting to the GCP bucket. The export job runs once an hour, so you're probably pulling the old version of a record if you download it as soon as the API response changes.

**Comment by jimshowalter** [comment]
An hour lag explains it. Just wanted to make sure you were aware of it. Typically the parity-check job passes, so we don't stress about it when it fails.
