### ISSUE TITLE
Details Page Does Not Display Vulnerability Summary

### ISSUE THREAD

**Issue by mhils** [google/osv.dev#2078]
**Describe the bug**

The details page for vulnerabilities currently does not include the summary description. This makes it hard to quickly grasp what the vulnerability is about.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://osv.dev/vulnerability/GHSA-6q4w-9x56-rmwq
2. Try to quickly grasp what this vulnerability is about.

**Expected behaviour**

The summary description that is displayed in the database list should be displayed prominently.

**Screenshots**

![image](https://github.com/google/osv.dev/assets/1019198/727574bd-d949-49c4-858a-43c0347349b0)

vs

![image](https://github.com/google/osv.dev/assets/1019198/005d2910-a8b1-4f6d-8e61-cc38359c4ea5)

**Comment by andrewpollock** [comment]
Looks like https://github.com/google/osv.dev/blob/98f798681f48eaf4bd0b2327d7e0857ade573b20/gcp/appengine/frontend3/src/templates/vulnerability.html#L9-L9 is operating on the wrong value?

**Comment by zahraaalizadeh** [comment]
I'm planning to work on this issue.
