### ISSUE TITLE
Add `osv-scanner fix` and GitHub actions to osv.dev home page.

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#2085]
We have examples of OSV-Scanner usages on the home page. We should expand them with guided remediation and GitHub actions.

**Comment by zahraaalizadeh** [comment]
@oliverchang I'm not sure of the exact acceptance criteria in this task. Do you mean we need to add some introduction text about the osv-scanner in the Home page? or just adding links of [announcing-guided-remediation-in-osv-scanner](https://osv.dev/blog/posts/announcing-guided-remediation-in-osv-scanner/) blog post or [guided remediation](https://google.github.io/osv-scanner/experimental/guided-remediation/) docs and [Github Actions](https://google.github.io/osv-scanner/github-action/) docs is enough?

**Comment by zahraaalizadeh** [comment]
Also, currently the `More details` button links to the `osv-scanner` github page. What do you think of updating it to the [osv-scanner documentation](https://google.github.io/osv-scanner/) instead.

**Comment by oliverchang** [comment]
> @oliverchang I'm not sure of the exact acceptance criteria in this task. Do you mean we need to add some introduction text about the osv-scanner in the Home page? or just adding links of [announcing-guided-remediation-in-osv-scanner](https://osv.dev/blog/posts/announcing-guided-remediation-in-osv-scanner/) blog post or [guided remediation](https://google.github.io/osv-scanner/experimental/guided-remediation/) docs and [Github Actions](https://google.github.io/osv-scanner/github-action/) docs is enough?

I mean adding some inline examples of invocations to `osv-scanner fix`, similar to how we have examples for "Scan SBOM or Lockfiles" and perhaps a screenshot of https://github.com/google/osv-scanner-action in actions. 

> Also, currently the `More details` button links to the `osv-scanner` github page. What do you think of updating it to the [osv-scanner documentation](https://google.github.io/osv-scanner/) instead.

Yes, that's a better link.

**Comment by zahraaalizadeh** [comment]
Thanks for the clarification. I'm planning to work on this issue.
