### ISSUE TITLE
Bioconductor enumeration code is fault-intolerant

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#2153]
**Describe the bug**
Bioconductor ecosystem test failures (due to the code under test being brittle) blocked unrelated PRs

**Expected behaviour**
A degree of _intermittent_ non-200 responses shouldn't cause immediate enumeration failure

https://requests.readthedocs.io/en/latest/user/advanced/#example-automatic-retries

Additionally, during periods of external infrastructure failure, the tests could fail open.

**Comment by andrewpollock** [comment]
/cc @tylfin FYI

We authored 
- https://github.com/google/osv.dev/blob/master/osv/ecosystems/bioconductor.py
- https://github.com/google/osv.dev/blob/master/osv/ecosystems/bioconductor_test.py

and haven't gotten around to addressing this yet. I wanted to ensure you were aware of this in case you/anyone else from the R Consortium have time and interest in assisting with addressing it before we get around to it.

**Comment by andrewpollock** [comment]
@hogo6002 can the work you did on enumeration make this code obsolete?

**Comment by hogo6002** [comment]
> @hogo6002 can the work you did on enumeration make this code obsolete?

I haven't replaced the API query for Bioconductor from the enumeration method to affected range comparison. If it consistently fails to enumerate versions for this ecosystem, I think we can switch to version range comparison very easily. Then, we probably won't need the enumeration code for this ecosystem.

**Comment by andrewpollock** [comment]
> we probably won't need the enumeration code for this ecosystem

Less (fault-intolerant, in particular) code SGTM 😺
