### ISSUE TITLE
Make it possible to visually evaluate a list of  vulnerabilities by severity

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#2255]
**Is your feature request related to a problem? Please describe.**
When viewing a list of vulnerabilities at https://osv.dev/list it is not possible to visually discern the severity of them

**Describe the solution you'd like**
- Sort by CVSS base score
- Have a graduated red background for each vulnerability's row based on severity

**Describe alternatives you've considered**
None, other than leaving as is.

**Additional context**
- https://pypi.org/project/cvss/ is probably relevant to the implementation for this

**Comment by zahraaalizadeh** [comment]
@another-rex Do we want to consider sorting feature for severity here too? Or this issue is resolved now?

**Comment by another-rex** [comment]
I think this is resolved for now. The sorting is a much more long term issue.

**Comment by another-rex** [comment]
FIxed in https://github.com/google/osv.dev/pull/2262
