### ISSUE TITLE
API: query vulnerabilities

### ISSUE THREAD

**Issue by pxp928** [google/osv.dev#2276]
**Describe the bug**

When querying with `curl "https://api.osv.dev/v1/vulns/ghsa-qc2g-gmh6-95p4"` it fails and returns a `Bug not found.` error. But when querying with `curl "https://api.osv.dev/v1/vulns/GHSA-qc2g-gmh6-95p4"` it ouputs the proper results. 

**To Reproduce**
```
curl "https://api.osv.dev/v1/vulns/ghsa-qc2g-gmh6-95p4"


{"code":5,"message":"Bug not found."}%
```

When the input is changed to `GHSA-qc2g-gmh6-95p4` (note: only change was GHSA was made capital)

`curl "https://api.osv.dev/v1/vulns/GHSA-qc2g-gmh6-95p4"` we get the proper output.

**Expected behavior**
query vulnerabilities API should be case-insensitive

**Comment by hogo6002** [comment]
Thanks for reporting this issue.
I think we want API query to be case sensitive as discussed in https://github.com/google/osv.dev/issues/1637. We will update docs to specify case sensitivity.
