### ISSUE TITLE
Display the correct affected versions when filtering by ecosystem

### ISSUE THREAD

**Issue by hogo6002** [google/osv.dev#2286]
**Describe the bug**
On the vulnerability list page, filtering by a specific ecosystem does not render the correct affected versions for that ecosystem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [vulnerability list](https://osv.dev/list?ecosystem=Alpine&q=)
2. Select "Alpine"
<img width="1196" alt="Screenshot 2024-06-06 at 2 13 11 PM" src="https://github.com/google/osv.dev/assets/39108850/9e8c503a-2fde-4e6d-a070-b9b0280078d5">
4. The affected versions displayed above are actually Debian versions, not the versions from the Alpine package.
<img width="1029" alt="Screenshot 2024-06-06 at 2 14 10 PM" src="https://github.com/google/osv.dev/assets/39108850/20559354-ae48-46ae-9d86-35f46e96b19f">

**Expected behaviour**
OSV.dev should only render affected versions for the specific ecosystem selected in the filter on the vulnerability list page.

**Comment by zahraaalizadeh** [comment]
The column is removed in https://github.com/google/osv.dev/pull/2262 so this issue can be considered as resolved.
