### ISSUE TITLE
Data Quality issue with GHSA-w9jx-4g6g-rp7x

### ISSUE THREAD

**Issue by clemens** [google/osv.dev#2331]
**Describe the bug**
The data for GHSA-w9jx-4g6g-rp7x includes `"type": 3` instead of `"type": "CVSS_V4"`.

**To Reproduce**
Steps to reproduce the behaviour:
1. `curl https://api.osv.dev/v1/vulns/GHSA-w9jx-4g6g-rp7x`
2. Check JSON at the very end

**Expected behaviour**
I'd expect the response to adhere to [declared schema](https://github.com/ossf/osv-schema/blob/live/validation/schema.json#L283-L305). So in this case it should show `"type": "CVSS_V4"`.

**Screenshots**
![Screenshot 2024-06-20 at 16 56 33](https://github.com/google/osv.dev/assets/3749/771266f9-467f-4162-ae77-d92ba53edcd5)

**Additional context**
I've come across this, because ORT started failing for TinyMCE and traced it back in [ORT's code](https://github.com/oss-review-toolkit/ort/blob/main/clients/osv/src/main/kotlin/Model.kt#L190-L200)

**Comment by michaelkedar** [comment]
The API should now be correctly returning "type": "CVSS_V4" in these cases.

Thanks for reporting this! Let us know if you're still encountering this issue.
