### ISSUE TITLE
GHSA-c5pj-mqfh-rvc3 Still in osv

### ISSUE THREAD

**Issue by zhangzhenyu2** [google/osv.dev#2332]
GHSA-c5pj-mqfh-rvc3 "Runc allows an arbitrary systemd property to be injected" is a misunderstood vulnerability. Users do NOT need to update runc

https://github.com/opencontainers/runc/issues/4263

but 
https://storage.googleapis.com/osv-vulnerabilities/index.html?prefix=Go/
Still in osv

**Comment by michaelkedar** [comment]
[The JSON record for GHSA-c5pj-mqfh-rvc3](https://storage.googleapis.com/osv-vulnerabilities/Go/GHSA-c5pj-mqfh-rvc3.json) has it marked as withdrawn - 
```
"id": "GHSA-c5pj-mqfh-rvc3",
"modified": "2024-06-05T18:30:34Z",
"published": "2024-04-26T06:30:34Z",

```

**Comment by andrewpollock** [comment]
Based on:

https://osv.dev/GHSA-c5pj-mqfh-rvc3 clearly marks the record as withdrawn
and
https://osv.dev/GHSA-c5pj-mqfh-rvc3.json has the `withdrawn` field set

I don't think there is anything actionable here. As @michaelkedar has pointed out, [the behaviour of the `withdrawn` field is documented in the FAQ](https://google.github.io/osv.dev/faq/#how-does-osvdev-handle-withdrawn-records) so I don't believe there is anything actionable here. Please reopen with specifics if you feel differently.
