### ISSUE TITLE
OSV API Response is Inconsistent with Schema

### ISSUE THREAD

**Issue by abhisek** [google/osv.dev#2337]
**Describe the bug**

The `severity[].type` field for a vulnerability in OSV schema is defined as `string`
https://github.com/ossf/osv-schema/blob/main/validation/schema.json#L320

However an integer is returned in the OSV API response breaking schema validation in consumer tools.

**To Reproduce**

- Request for vulnerabilities affecting `js2py==0.74` 

```
curl -s -d \
  '{"package": {"name": "js2py", "ecosystem": "PyPI"}, "version": "0.74"}' \
  "https://api.osv.dev/v1/query" | jq '.vulns[0].severity'
```

- Observe numeric type in response

```
{
    "type": 3,
    "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N"
  }
```

**Expected behaviour**

As per schema, `type` should be a string enum

```
CVSS_V2
CVSS_V3
CVSS_V4
```

**Screenshots**

<img width="781" alt="Screenshot 2024-06-24 at 2 49 22 PM" src="https://github.com/google/osv.dev/assets/31844/d1699ad7-08f2-43d2-9f24-eaf0bbced22b">

**Additional context**

N/A

**Comment by abhisek** [comment]
This issue seems to be data quality issue and related to https://github.com/google/osv.dev/issues/2331

**Comment by michaelkedar** [comment]
The API should now be correctly returning `"type": "CVSS_V4"` in these cases.

Thanks for reporting this! Let us know if you're still encountering this issue.
