### ISSUE TITLE
Request vulnerability of multiple package in the same request

### ISSUE THREAD

**Issue by enzofrnt** [google/osv.dev#2380]
**Is your feature request related to a problem? Please describe.**
Yes, for now, the only way to get vulnerability of multiple packages is by "spamming" the `/v1/query` URL of the API.

**Describe the solution you'd like**
A new endpoint that make this possible, and returning the full vuln and not just the id.
Or, the possibility to send and array of wondering package vulns on the `/v1/query` URL.

**Additional context**
That maybe really useful to analyze our things…

**Comment by another-rex** [comment]
We do have a batch query endpoint: https://google.github.io/osv.dev/post-v1-querybatch/ , is this what you are looking for?

**Comment by andrewpollock** [comment]
To expand on this, the expected user journey is:

1. Issue a [querybatch](https://google.github.io/osv.dev/post-v1-querybatch/) request
2. Issue a [vulns](https://google.github.io/osv.dev/get-v1-vulns/) request for each ID returned

**Comment by enzofrnt** [comment]
> To expand on this, the expected user journey is:
> 
> 
> 
> 1. Issue a [querybatch](https://google.github.io/osv.dev/post-v1-querybatch/) request
> 
> 2. Issue a [vulns](https://google.github.io/osv.dev/get-v1-vulns/) request for each ID returned

thank you but that mean that when we have a lot of vuln we will be "spamming" the API ?

**Comment by andrewpollock** [comment]
> that mean that when we have a lot of vuln we will be "spamming" the API ?

This is the intended use case and not considered "spam". See also https://google.github.io/osv.dev/api/#is-the-api-rate-limited.

The alternative would be a potentially enormous single response message to an arbitrarily large querybatch request.

Given your need can be met by the current API endpoints using the the user journey described, I'll close this.
