### ISSUE TITLE
Data quality issue with GO-2024-2521

### ISSUE THREAD

**Issue by Itxaka** [google/osv.dev#2389]
**The CVE ID**
https://osv.dev/vulnerability/GO-2024-2521

**Describe the data quality issue observed**
Report mentions that the version affected is 19.3.0 and was fixed on 19.03.1 but the scan comes back reporting this on higher versions:

```
{
    "custom_ranges": [
        {
            "events": [
                {
                    "introduced": "19.03.0"
                },
                {
                    "fixed": "19.03.1"
                }
            ],
            "type": "ECOSYSTEM"
        }
    ]
}
```

```
╭──────────────────────────────┬──────┬───────────┬──────────────────────┬─────────────────────┬────────╮
│ OSV URL                      │ CVSS │ ECOSYSTEM │ PACKAGE              │ VERSION             │ SOURCE │
├──────────────────────────────┼──────┼───────────┼──────────────────────┼─────────────────────┼────────┤
│ https://osv.dev/GO-2024-2521 │      │ Go        │ github.com/moby/moby │ 24.0.9+incompatible │ go.mod │
╰──────────────────────────────┴──────┴───────────┴──────────────────────┴─────────────────────┴────────╯

```

**Suggested changes to record**
Should not match versions higher than 19.03.1

**Additional context**

**Comment by andrewpollock** [comment]
Looking at https://vuln.go.dev/ID/GO-2024-2521.json there's a mismatch between what's in `.affected[].ranges[]` (which should be used for determining the applicability) and `.affected[].ecosystem_specific`

I've brought this to the Go security team's attention.

**Comment by andrewpollock** [comment]
The record has been corrected at the source and there is now a `fixed` version in the record in OSV.dev

**Comment by Itxaka** [comment]
Thank you @andrewpollock !
