### ISSUE TITLE
Support API queries for non-enumerated ecosystems

### ISSUE THREAD

**Issue by hogo6002** [google/osv.dev#2401]
Enable OSV.dev API queries for specific versions in non-enumerated ecosystems (e.g., Ubuntu, Rocky Linux, AlmaLinux).

```
curl -d '{"package": {"name": "curl", "ecosystem": "Ubuntu"}, "version": "8.2.1-1ubuntu3.1"}' http://api.osv.dev/v1/query
```

**Comment by oliverchang** [comment]
I think we can close this as done @hogo6002  ?
