### ISSUE TITLE
Missing `Packages` for some malicious packages 

### ISSUE THREAD

**Issue by hogo6002** [google/osv.dev#2422]
**Describe the bug**
Some malicious packages don't have `package` name list on vulnerability list page.

**Expected behaviour**
The related package names should be shown

**Screenshots**
![image](https://github.com/user-attachments/assets/6da34d69-360f-471c-81e6-ee9e2d5959ab)

**Additional context**
All affected ones are those without `affected_range`, example: https://osv.dev/vulnerability/MAL-2024-7844

**Comment by neehhaa06** [comment]
Hello @hogo6002 

fix: #2422

### Check affected_range: If affected_range is available, display it. Otherwise, show "Not specified" to indicate the missing information.
