### ISSUE TITLE
Combine all `not yet assigned` Debian Security Tracker issues into OSV

### ISSUE THREAD

**Issue by hogo6002** [google/osv.dev#2482]
OSV [doesn't combine issues ](https://github.com/google/osv.dev/blob/02575ef484fe7fd5b88e38f347163062d53df30c/vulnfeeds/cmd/debian/main.go#L114)with the `not yet assigned` urgency tag from the Debian Security Tracker because we thought the status of those issues might change soon. But we've observed that many vulns remain in this stage for a very long time, and it doesn't seem like their status will change.

Confirmed with the Debian Security Team via email that they no longer assign urgencies to security issues, only some legacy ones with low/medium/high tags. For all issues without an assigned urgency, we should treat them as regular security issues and merge them into OSV. 

A very large number of issues have `not yet assigned` tag (around 10k), but not all are valid entries (some may not affect any release)

**Comment by carnil** [comment]
FWIW, we have updated our documentation for the current practice with https://salsa.debian.org/security-tracker-team/security-tracker/-/commit/ee436d666e0fb8cf845de22b012efe539d13d116
