### ISSUE TITLE
Ingest SUSE/openSUSE OSV advisories

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#2543]
Per https://github.com/ossf/osv-schema/issues/259, the SUSE/openSUSE ecosystems have been added to the OSV schema, and there is a feed available at https://ftp.suse.com/pub/projects/security/osv/

**Comment by oliverchang** [comment]
For version ordering, SUSE seems to use RPM (https://en.opensuse.org/openSUSE:Package_versioning_guidelines).

For https://ftp.suse.com/pub/projects/security/osv/, we may need an `https://ftp.suse.com/pub/projects/security/osv/all.json` per https://google.github.io/osv.dev/rest-api-contribution/#1-a-url-pointing-to-a-rest-endpoint-containing-at-least-all-of-the-vulnerabilities-ids-and-date-modified. @msmeissn is this something that would be possible to add?

**Comment by msmeissn** [comment]
i added an all.json file now.

**Comment by oliverchang** [comment]
Thanks @msmeissn ! 

@hogo6002 can you see if we can start ingesting this into our test instance?

**Comment by hogo6002** [comment]
Hey @msmeissn, I have a question about the data prefixes and would like some clarification.

The ossf schema lists the valid prefixes for [SUSE as only `SUSE-SU-`](https://ossf.github.io/osv-schema/#id-modified-fields), but I noticed that `all.json` also contains entries other than `SUSE-SU-` (security updates), such as `SUSE-RU-` (recommended updates) and `SUSE-FU-` (feature updates). 

I just want to confirm if we only want to ingest data with the `SU-` prefix into OSV or if we want to ingest all the data from `all.json` into OSV.

Also, I'm wondering if entries with other prefixes, such as `SUSE-RU-` and `SUSE-FU-`, are actually security-related data (they do have related CVEs on their records)?

**Comment by msmeissn** [comment]
ok, problem is that occasionaly "recommended (bugfix)" or feature updates also include CVEs and I generate entries for those. Note that only bugfix or freature updates that have CVEs will be reported for OSV.

I sent a PR to osv-schema to allow them, so we can consume those.

**Comment by hogo6002** [comment]
> I sent a PR to osv-schema to allow them, so we can consume those.

Thanks! I will start to ingest data into our test instance.

**Comment by hogo6002** [comment]
SUSE/openSUSE data is available on **test.osv.dev** now!
website: https://test.osv.dev/list?q=&ecosystem=SUSE https://test.osv.dev/list?q=&ecosystem=openSUSE
API query:
`curl -d \
  '{"version": "1.2.0~rc3",
    "package": {"name": "runc", "ecosystem": "openSUSE"}}' \
  "https://api.test.osv.dev/v1/query"`

**Comment by hogo6002** [comment]
SUSE/openSUSE is now on osv.dev!

**Comment by hogo6002** [comment]
Hi @msmeissn ,

It looks like the PURL field for SUSE/openSUSE records might be incorrect. Could you take a look?

- PURLs should start with `pkg:` (e.g. `pkg:`), not `purl:`. (example: https://osv.dev/vulnerability/openSUSE-SU-2024:0374-1)
- PURLs of openSUSE records start with `purl:rmp/suse` rather than `pkg:rpm/opensuse`. Is this expected? It would be better to match its ecosystem.

Could you help update these to align with the [PURL spec](https://github.com/package-url/purl-spec)? The "distro" string format might also need a look, but that's less important since we don't currently support distro-specific queries.

[PURL spec](https://github.com/package-url/purl-spec):
`pkg:rpm/opensuse/curl@7.56.1-1.1.?arch=i386&distro=opensuse-tumbleweed` (version is not needed for our use case. arch and distro are optional for osv)

**Comment by msmeissn** [comment]
i fixed this in the script. will be regenerarted next night

**Comment by msmeissn** [comment]
(purl: -> pkg: , and the opensuse ones report rpm/opensuse/

**Comment by hogo6002** [comment]
Hi @msmeissn, thanks for fixing the PURL issue. While most records now show the corrected PURL field, there are still a few with the incorrect PURL, such as:
https://ftp.suse.com/pub/projects/security/osv/SUSE-RU-2024:3971-1.json (begins with `purl:`)
https://ftp.suse.com/pub/projects/security/osv/SUSE-FU-2024:2078-1.json (begins with `purl:`)

Could you take a look at this again? My guess is that all the unfixed records are `SUSE-RU-` and `SUSE-FU-` types, while all the `SU-` records have been fixed.
