### ISSUE TITLE
Data quality issue with https://osv.dev/vulnerability/PYSEC-2024-71

### ISSUE THREAD

**Issue by edufresne** [google/osv.dev#2568]
It looks like this issue was solved in fix version: 5.0.0 but this vulnerability is still labelled as 5.* as an affected version.

**Additional context**
Looking at the flask-cors last 5.0.0 release, it looks to have addressed this issue:
- https://github.com/corydolphin/flask-cors/releases/tag/5.0.0
- https://github.com/corydolphin/flask-cors/pull/368

Should this vulnerability be marked as having a fix version? Maybe this is an issue with the project itself and not a data integrity issue?

**Comment by MindaugasBernatavicius** [comment]
Indeed, this affects pip-audit results and delays "time to resolution" metrics in environments that track this for auditing purposes.

Issue alias is listed as "fix available": https://osv.dev/vulnerability/GHSA-hxwh-jpp2-84pm . PYSEC-2024-71 has it's import datasource as: https://github.com/pypa/advisory-database/blob/main/vulns/flask-cors/PYSEC-2024-71.yaml from pypa advisory. Pypa say that they use nist feeds https://nvd.nist.gov/vuln/data-feeds and this tool: https://github.com/google/osv.dev/tree/master/vulnfeeds - to match vulnerabilities by ids or something like that. 

Does this need to be fixed upstream in Pypa advisory repo? Or even the original vuln report: https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d ?

**Comment by hogo6002** [comment]
> PYSEC-2024-71 has it's import datasource as: https://github.com/pypa/advisory-database/blob/main/vulns/flask-cors/PYSEC-2024-71.yaml from pypa advisory.

That is correct. It's imported from upstream, including the affected versions.

> Does this need to be fixed upstream in Pypa advisory repo? Or even the original vuln report: https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d ?

Yes, it will need to be fixed in the PyPa advisory repo first. I guess we don't have anything to do here until upstream fixes this. Do you have anything to add on this issue @andrewpollock ?

**Comment by andrewpollock** [comment]
Yes, from OSV.dev's perspective, the upstream record is https://github.com/pypa/advisory-database/blob/main/vulns/flask-cors/PYSEC-2024-71.yaml and should be corrected by following https://github.com/pypa/advisory-database?tab=readme-ov-file#contributing-advisories
