### ISSUE TITLE
Request appears to be getting rate-limited?

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#2680]
**Describe the bug**
The documentation says the API isn't rate-limited, but this happened:

![Screenshot 2024-09-30 at 10 47 09 AM](https://github.com/user-attachments/assets/e0c06ad6-5d05-43fa-955e-b87d0d009058)

https://osv.dev/vulnerability/GHSA-735f-pc8j-v9w8

Too Many Requests
This user has exceeded an allotted request count. Try again later.

Was rate limiting recently added?

We don't really hit the endpoint very often.

**Comment by jimshowalter** [comment]
This exposed an inefficiency in our custom Gradle plugin. We were running it on all subprojects in a large multi-module repo, instead of just once on the root project.

**Comment by andrewpollock** [comment]
Hi Jim,

It'd be interesting to have seen the HTTP headers on that response. We still have no explicitly configured rate limiting for our API (I note that based on the screenshot, this wasn't from accessing the API, it was from the web interface).

I'm unsure about any baked-in DoS protections that Google Cloud may have for the components we use for serving, though.

**Comment by jimshowalter** [comment]
Interesting. If it happens again I'll save the info.
