### ISSUE TITLE
DLA-3911-1, DLA-3912-1 missing in OSV.dev all.zip

### ISSUE THREAD

**Issue by WiTe0DeViL** [google/osv.dev#2708]
DLA-3911-1, DLA-3912-1 missing in OSV.dev all.zip file downloaded from osv-vulnerabilities.storage.googleapis.com

<img width="600" alt="image" src="https://github.com/user-attachments/assets/20495e68-06f0-4931-9cc9-697f638fecfc" />

<br/><br/>

Debian reference for same DLAs

- [DLA-3911-1](https://lists.debian.org/debian-lts-announce/2024/10/msg00002.html)

<img width="600" alt="Screenshot 2024-10-08 at 11 12 37 AM" src="https://github.com/user-attachments/assets/9a3aeff0-904e-47de-b1a2-18a53abb73bd" />

- [DLA-3912-1](https://lists.debian.org/debian-lts-announce/2024/10/msg00003.html)

<img width="600" alt="Screenshot 2024-10-08 at 11 12 14 AM" src="https://github.com/user-attachments/assets/4f94e7bf-4a17-490f-8d3e-337d61611002" />

<br/><br/>

Kindly clarify on these please.

**Comment by another-rex** [comment]
Thanks for letting us know! Our exporter is currently facing some performance issues at the moment causing it to not update all.zip correctly, but it should be fixed soon (within this week)!

**Comment by WiTe0DeViL** [comment]
Thankyou for the quick response, Please do update after the fix
