### ISSUE TITLE
Corrections Needed for Several Malware Attributions

### ISSUE THREAD

**Issue by behnazh-w** [google/osv.dev#2729]
**Describe the bug**
As part of the [Macaron](https://github.com/oracle/macaron) package, we have identified several malicious Python packages in your records that have been incorrectly attributed to ReversingLabs as the FINDER. Two examples are the [manyhttps](https://osv.dev/vulnerability/MAL-2024-5350) and [multiconnection](https://osv.dev/vulnerability/MAL-2024-5383) packages. We are happy to provide confirmation emails from the PyPI security team for our reports. How can we share this information to update your records?

**Comment by hogo6002** [comment]
Hi @behnazh-w, thanks for reporting!

OSV gets all malicious package information from [upstream](https://github.com/ossf/malicious-packages). To correct the [record](https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/manyhttps/MAL-2024-5350.json), could you please raise an issue there to provide feedback directly to the record's originator?

**Comment by behnazh-w** [comment]
Thank you, @hogo6002. I have opened an issue in the upstream repository: https://github.com/ossf/malicious-packages/issues/660.

**Comment by hogo6002** [comment]
Thanks Behnaz! Close this issue for now, feel free to reopen it if  you have any other issues.
