### ISSUE TITLE
ALEA-2021:4152 Missing affected field

### ISSUE THREAD

**Issue by Aviramasraf** [google/osv.dev#2763]
**Describe the bug**
When reviewing [ALEA-2021:4152](https://osv.dev/vulnerability/ALEA-2021:4152) I've noticed the crucial 'affected' field is missing. This is probably because the reference is also missing this critical information (https://errata.almalinux.org/8/ALEA-2021-4152.html). 
I'm unsure if it is considered a 'bug,' but I've checked, and this is the only vulnerability in OSV without the affected field. 

**To Reproduce**
Just review the link of the vulnerability

**Expected behaviour**
Relevant affected packages or software should be described. I tried to understand if the affected field is mandatory from the documentation, but I could not verify that. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/1c2e2d29-37e4-42fd-804e-e746ceb39c8e)

**Comment by andrewpollock** [comment]
@Roo4L FYI
