### ISSUE TITLE
grpc-backend running out of memory

### ISSUE THREAD

**Issue by another-rex** [google/osv.dev#2765]
Tracking issue for the GRPC out of memory error. We likely need to bump the memory given the recent large OSV records we are now serving.

**Comment by another-rex** [comment]
Manually bumped the memory to 8Gb from 4Gb, and will continue monitoring

**Comment by another-rex** [comment]
This seems to have stopped OOM errors now, though there is a lot of 20 second queries now at 99%> . Theory is that this is caused by the paging limit correctly kicking in and preventing a timeout, and now that there is more memory these requests are not killed by OOM.

**Comment by andrewpollock** [comment]
@another-rex is this okay to close now?
