### ISSUE TITLE
Migrate Datastore Bug keys after removing logic to create source-specific keys

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#2786]
In https://github.com/google/osv.dev/pull/2435, we stopped creating `Bug` ndb Keys with a `source_id:bug ID` format. 

However, existing entities might still have this, and should be migrated so we can delete `db_id` completely and just rely on the NDB key.

**Comment by andrewpollock** [comment]
FYI https://github.com/search?q=repo%3Agoogle%2Fosv.dev+path%3A%2F%5Etools%5C%2Fdatafix%5C%2F%2F+db_id&type=code is relying on `db_id` so will require reworking to accommodate.
