### ISSUE TITLE
Invalid PURL for conan package

### ISSUE THREAD

**Issue by trew** [google/osv.dev#2960]
**Describe the bug**
Since https://github.com/google/osv.dev/commit/7496fb42f9302c15607920e60ddc50c7a7fae98d the API no longer accepts the conan PURLs, for example: `pkg:conan/openssl@3.0.3`

I guess parsing this PURL returned None previously, but now it raises ValueError.

**To Reproduce**
Steps to reproduce the behaviour:
1. `curl -d '{"package": {"purl": "pkg:conan/openssl@3.0.3"}}' "https://api.osv.dev/v1/query"`
2. Response is `{"code":3,"message":"Invalid PURL."}`

**Expected behaviour**
Some kind of response with response code 200

**Comment by nchelluri** [comment]
I am not 100% sure that the commit mentioned here is the culprit for this, but I see the same response with this PURL: pkg:github/actions/checkout@v1 . I am sure it was not like this a few days ago. I don't know if pkg:github would be considered a valid PURL.

**Comment by hogo6002** [comment]
Hi @trew and @nchelluri, thanks for reporting this!

The issue was caused by the PURL API refactoring, where we added PURL ecosystem validation. Because we lack Conan and GitHub Actions PURL converters, the system failed to extract the ecosystem name from the PURL string and treated the queries as invalid. I will do a fix release soon to address this issue.

**Comment by hogo6002** [comment]
I have deployed the fix. PURL queries for Conan and GitHub Actions should no longer raise any errors. If you have any other questions, please let me know. Thanks again for the report!

**Comment by trew** [comment]
> I have deployed the fix. PURL queries for Conan and GitHub Actions should no longer raise any errors. If you have any other questions, please let me know. Thanks again for the report!

Thank you so much for the quick resolution! Works as expected from my side now 👍
