### ISSUE TITLE
Bad CRC in GHSA-8qv4-773j-c979.json

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#2966]
**Describe the bug**
Our vulns checker failed with this error:

`Unable to unzip Maven_all.zip to maven-vulns-from-remote-zip: Reached end of entry, but crc verification failed for GHSA-8qv4-773j-c979.json`

**To Reproduce**
Steps to reproduce the behaviour:
1. Try unzipping it manually.

**Expected behaviour**
The unzip operation should succeed.

**Comment by cuixq** [comment]
@jimshowalter can you provide more details regarding this issue? I tried to unzip `Maven_all.zip` and it works for me with no error.

**Comment by jimshowalter** [comment]
It's just what I described--code that normally downloads and unzips Maven_all.zip ran into that error instead.

It seems to have magically healed itself.

**Comment by oliverchang** [comment]
Closing since we don't have a reproducer to investigate this. Please let us know if you see this again.
