### ISSUE TITLE
CI scanning actions

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#412]
Tracking bug for CI scanning actions. These actions should:

1. Scan all project dependencies against OSV
2. Provide guided remediation steps, or automatic remediation PRs.

**Comment by andrewpollock** [comment]
Could you please elaborate? How does this relate to #57?

**Comment by oliverchang** [comment]
Added a bit more detail, and closed #57 which was different and not something we'd want to do.

**Comment by oliverchang** [comment]
this has launched in https://github.com/google/osv-scanner-action
