### ISSUE TITLE
Missing data from GitHub Advisory Database 

### ISSUE THREAD

**Issue by maitrayshah** [google/osv.dev#467]
Hi, I was checking for delta between vulnerabilities available in Github Advisory and OSV and found that it might be missing some advisories published on Github.

For example - I came across [Improper Input Validation](https://github.com/advisories/GHSA-8489-44mv-ggj8) and was not able to find that ID in [OSV UI](https://osv.dev/list?ecosystem=&q=) or [GCS Bucket](https://osv-vulnerabilities.storage.googleapis.com). I can pull the entire list if need and appreciate the help.

**Comment by oliverchang** [comment]
The core issue is that a small handful GHSA entries use the ">" operator to describe affected ranges which is not always defined in a consistent way. My understanding is this is avoided in most cases, and we can always suggest improvements to the GHSA entry to avoid that operator.

**Comment by maitrayshah** [comment]
Thanks for the quick response @oliverchang. Glad to know this is a known issue. Feel free to close this issue since its being tracked already.
