### ISSUE TITLE
Pagination is not constrained to the max number of pages (resulting in no results showing)

### ISSUE THREAD

**Issue by G-Rath** [google/osv.dev#468]
Bit of an awkward title, but in a nutshell the osv list seems to assume the `page` param value is correct even if there's less pages for a particular database leading to no vulnerabilities being shown even though the database counters say there should be, and it's not obvious why:

![image](https://user-images.githubusercontent.com/3151613/175754952-218c5cfb-bb92-4511-a677-be4cef052baa.png)

https://osv.dev/list?page=2&ecosystem=DWF&q=

I can get into this state by viewing the vulnerabilities for a database that has pages, then switching to one that has less pages.

**Comment by oliverchang** [comment]
Thanks! This is indeed something we need to fix :)

**Comment by donchkat** [comment]
I don't know if it's related, but I noticed two days ago that the number of records in the website is higher than the number you get from an API call for every ecosystem. The size of the gap can be 2 records or 2000 records...
Example:
The request I sent : https://osv-vulnerabilities.storage.googleapis.com/Linux/all.zip 
As a result I got only 5321 records in this zip file, while in the site the number of linux records is 7657.
Maybe I'm missing something here or understanding something wrong?

**Comment by oliverchang** [comment]
> I don't know if it's related, but I noticed two days ago that the number of records in the website is higher than the number you get from an API call for every ecosystem. The size of the gap can be 2 records or 2000 records... Example: The request I sent : https://osv-vulnerabilities.storage.googleapis.com/Linux/all.zip As a result I got only 5321 records in this zip file, while in the site the number of linux records is 7657. Maybe I'm missing something here or understanding something wrong?

Our counts are currently a rough overestimate -- it does not exclude any withdrawn/invalid entries. The dump would have the more accurate numbers. I've opened https://github.com/google/osv/issues/471 for this.

**Comment by another-rex** [comment]
Having the `?page` parameter seem to cause another related issue, loading a page with the page parameter, or refreshing a page after pressing "load more" a few times, will only display that page, with no option of going back to previous pages, and no indication that you are missing some results.

I propose either switching to a more standard pagination UI (preferred). or removing the page parameter from the URL.
