### ISSUE TITLE
Add a caching layer to `ecosystems`

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#488]
To reduce API load when we retrieve lists of versions for packages in our ecosystems code.

**Comment by oliverchang** [comment]
One way to do this might be to add a `set_cache` method to https://github.com/google/osv.dev/blob/57ac34b2f15a80c584a8fa02a50d16e6fc4e10fc/lib/osv/ecosystems.py. This would need an interface defined for what methods that cache object needs to support.

If set, `Ecosystem` implementations can that cache.

**Comment by another-rex** [comment]
Debian caching completed, implementing additional caching for other ecosystems is continued in #498
