### ISSUE TITLE
Get vulnerability by ID has non-deterministic property ordering

### ISSUE THREAD

**Issue by fviernau** [google/osv.dev#495]
Probably minor: Subsequent request of the vulnerability with `id=GHSA-xvch-5gv4-984h"` has alternating ordering of the properties of the `database_specific` JSON object.

**Comment by oliverchang** [comment]
I'm not sure if we can easily ensure deterministic order of fields here.

Does this cause any problems for you?

**Comment by fviernau** [comment]
This does not cause any problems. IMO code should not make assumptions about ordering of JSON elements.
It was just meant as minor nice-to-have for development, e.g. to easily see if results are same.

**Comment by oliverchang** [comment]
Thanks for clarifying, I'll close this for now.
