### ISSUE TITLE
Normalize PyPI packages from sources. 

### ISSUE THREAD

**Issue by xu1119** [google/osv.dev#508]
### Description
PyPI package names are case insensitive. When search vulnerability by ID GHSA-jwqp-28gf-p498, here are two  affected packages: Scrapy and scrapy, but they are the same one package.

https://osv.dev/list?ecosystem=&q=GHSA-jwqp-28gf-p498
![image](https://user-images.githubusercontent.com/26019024/178423477-0fdbb1f4-35a0-443c-b6bb-6951718ea542.png)

**Comment by oliverchang** [comment]
Hi, 

Thanks for reporting this. This is a known issue (https://github.com/ossf/osv-schema/pull/42) on the GitHub advisories side. My understanding is that this may take some time to fix on their end. 

We could also potentially normalize this ourselves, so I'll keep this open as a FR for that.
