### ISSUE TITLE
Data dumps seem to be more than a week out of date (maybe even a month?)

### ISSUE THREAD

**Issue by G-Rath** [google/osv.dev#524]
I know that the data dumps are not expected to be as up to date as the API, but iirc it was only expected to always be a few hours out of date whereas right now it looks like its at least 10 days.

I noticed this as `osv-detector` was saying it had last updated its databases "Tue, 05 Jul 2022" for at least the RubyGems and npm databases, and at least GHSA-crrq-vr9j-fxxh, GHSA-3hhc-qp5v-9p2j, and GHSA-pg8v-g4xq-hww9 are missing in the latest version of the data dumps - the last of those being created 22 days ago.

**Comment by G-Rath** [comment]
I'm wondering if this is because of #451 - maybe the source of the data dumps is still pointed at the fork, which is not being updated?

**Comment by oliverchang** [comment]
Thanks for flagging! It looks like our exporter was running out of memory without indicating so on kubernetes. We've bumped the memory and we seem to be getting everything uploaded now. 

We're planning a number of monitoring and reliability improvements this quarter to prevent this from happening again.

**Comment by G-Rath** [comment]
@oliverchang it looks like this has happened again a few days after you closed this - these advisories are missing:
  * GHSA-mhxj-85r3-2x55 (npm, published 6 days ago)
  * GHSA-42m6-g935-5vmq (npm, published 2 days ago)
  * GHSA-m58q-qq5h-mgqq (composer/Packagist, published 6 days ago)
  * GHSA-5qj8-6xxj-hp9h (composer/Packagist, published 9 days ago)

**Comment by oliverchang** [comment]
Thanks for flagging once more. Looks like we inadvertendly reverted our memory bump. We've bumped it back once more.
