### ISSUE TITLE
Debian: overlapping versions

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#529]
e.g. on https://osv.dev/vulnerability/DSA-5087-1

"2.1.27+dfsg-1+deb10u2" is the fixed version for Debian 10. However, Debian 11 includes "2.1.27+dfsg-1+deb10u2" in the list of affected versions. 

We may need to do some filtering based on the +debXXuX" string here while enumerating for a particular Debian release.

**Comment by another-rex** [comment]
Some of the older debian releases actually don't use the `+debXXuX` syntax, but use `+<codename>uX`. For example:
`2.1.22.dfsg1-23+squeeze1`.
