### ISSUE TITLE
OpenAPI specification doesn't match API

### ISSUE THREAD

**Issue by JamieMagee** [google/osv.dev#542]
I'm currently building a .NET client library for OSV[^1]. I started out using the OpenAPI schema[^2], but it appears to be out of date. The `package` property in the `osvVulnerability` object doesn't exist in API responses.

https://github.com/google/osv.dev/blob/ac719f1efee4d687ebd8c52b99d728c5b66f15fc/docs/osv_service_v1.swagger.json#L337-L344

Is it possible to regenerate the OpenAPI schema? I'm not sure if there are any other discrepancies, as I haven't finished writing the library yet. 

[^1]: https://github.com/JamieMagee/osv.net
[^2]: https://osv.dev/docs/osv_service_v1.swagger.json

**Comment by oliverchang** [comment]
Thanks for filing this @JamieMagee ! 

Are you talking about the bulk API in particular, where the responses aren't hydrated? The `package` property should be returned almost 100% of the time from the other endpoints.

**Comment by oliverchang** [comment]
Ah, I misunderstood the issue here -- you're talking about the top level `package` property, which we deprecated. I'll remove it.

**Comment by JamieMagee** [comment]
Yep, that's the one. Thanks!
