### ISSUE TITLE
schema: Move the `severity` from `Vulnerability` into the respective `Affected`

### ISSUE THREAD

**Issue by fviernau** [google/osv.dev#545]
Vulnerability has the arrays `severity` and `affected`. I couldn't find the documentation for these arrays, but my guess is that
the _i-th_ `severity` entry corresponds to the package referenced by the _i-th_ entry in `affected`.

Can you confirm that above assumption is true? 
If so, would it make sense to change the schema as follows?

from:
```
Vulernability (
  ...  
  severity[]
  affected[]
  ...
)
```

to: 
```
Vulernability (
  ...  
  affected[]
  ...
)

Affected(
  ...
  severity
  ...
)
```

**Comment by oliverchang** [comment]
Hi! 

This assumption is not correct -- the `severity` field is an array only to account for multiple scoring algorithms (currently only CVSS is supported). 

I think we need some clarification on the spec (https://ossf.github.io/osv-schema/#severity-field) here?

**Comment by another-rex** [comment]
Close since moved over to osv-schema
