### ISSUE TITLE
PyPA/PyPA integration is offline?

### ISSUE THREAD

**Issue by woodruffw** [google/osv.dev#552]
Hey there!

I'm triaging some 404s that PyPI is seeing from osv.dev's `/public_keys/pypa` endpoint:

```console
$ http https://osv.dev/public_keys/pypa
HTTP/1.1 404 Not Found
Content-Length: 293
Content-Type: text/html; charset=UTF-8
Date: Mon, 25 Jul 2022 15:32:22 GMT
Server: Google Frontend
X-Cloud-Trace-Context: 58292526f14f9b975c32d17a6245ff73

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
<h2>The requested URL <code>/public_keys/pypa</code> was not found on this server.</h2>
<h2></h2>
</body></html>
```

If I'm reading the code correctly, this endpoint _should_ be returning a JSON payload that looks roughly like this instead:

```json
{
  "public_keys": [
    {
      "key_identifier": "da1e5968f30808f0edae0882b46d3282edb691cb8b46be04840aaa2f7f5bf162",
      "key": "-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6ZUVCBpniyHqjA4ZiYskxrkLaGi5f+Ra\ngex175FOARaoUkFXrSIY0ULJO4hUYuYYHdVyDytfT3PKVevs/kPvSA==\n-----END PUBLIC KEY-----\n",
      "is_current": true
    }
  ]
} 
```

It looks like the `/public_keys/` route is still defined in `app.yaml`:

https://github.com/google/osv.dev/blob/c6eca0a74a750ab8af2c5e99dfd97beb5acb1d7b/gcp/appengine/app.yaml#L34-L36

...but I can't find a corresponding path in the repository for the `pypa` public key. Maybe it was accidentally removed?

**Comment by woodruffw** [comment]
xref https://github.com/pypi/warehouse/issues/11951

**Comment by oliverchang** [comment]
Thanks for flagging @woodruffw ! I've added the key in https://github.com/google/osv.dev/pull/553 and redeployed it.

**Comment by woodruffw** [comment]
Thanks! I can confirm that I'm able to retrieve the key once more.
