### ISSUE TITLE
List of libraries and API clients

### ISSUE THREAD

**Issue by JamieMagee** [google/osv.dev#559]
In a similar vain to #464, I think it might be useful to make a list somewhere of libraries that implement the OSV schema or an OSV API client to prevent reinventing the wheel.

So far I've come across:
- Rust
  - https://github.com/gcmurphy/osv
- Go
  - https://pkg.go.dev/golang.org/x/vuln/osv
  - https://github.com/G-Rath/osv-detector
- .NET
  - https://github.com/JamieMagee/osv.net (`OSV.Schema` and `OSV.Client` packages)

But it's not exhaustive, and [a quick GitHub search for `api.osv.dev`][1] shows more results

[1]: https://github.com/search?q=%22api.osv.dev%22&type=code

**Comment by oliverchang** [comment]
Thanks! This is a great point. 

We already have a section at https://github.com/google/osv.dev#third-party-tools that we could expand on. Feel free to create a PR for this, or we can do this next week once we're back from a team event.

**Comment by oliverchang** [comment]
@andrewpollock do you wanna make this documentation change too?

**Comment by andrewpollock** [comment]
Ack, I'll get onto this this week

**Comment by andrewpollock** [comment]
I mentioned the wrong thing on https://github.com/google/osv.dev/pull/596, this is fixed now.

For the record, the search results also included a bunch of forks from the OSV repo, so it's artificially higher than reality.
