### ISSUE TITLE
Add the data from mass-scanning python projects with bandit

### ISSUE THREAD

**Issue by KOLANICH** [google/osv.dev#58]
* https://github.com/PyCQA/bandit
* https://bandit.readthedocs.io/

**Comment by andrewpollock** [comment]
Hi @KOLANICH it sounds like from reading [this paper](https://arxiv.org/pdf/2107.12699.pdf) that a one time analysis was performed. A couple of clarifying questions:

1) do you know where the findings from this paper are?
2) is anyone continuously running Bandit, in the same sort of way that OSS Fuzz is continuously fuzzing OSS?

**Comment by oliverchang** [comment]
Closing for the same reason as #57.
