### ISSUE TITLE
Installation of osv-scanner does not work ( ubuntu / osx )

### ISSUE THREAD

**Issue by liorkesos** [google/osv.dev#603]
Hi guys , I'm a newbie to Go so have installed go just to run the scanner.
I've tried both in Linux and OSX and it does not work for me in either environment.
I might be missing something trivial and I would be  glad to send a PR with the proper documentation when I figure out what I'm doing wrong...
I'm pastng the outputs for both environments
Linux - Ubuntu 20.04.4 LTS
```
> snap install go --classic
> go install github.com/google/osv/tools/osv-scanner@latest
go: downloading github.com/google/osv v0.0.14
go: downloading github.com/google/osv/tools/osv-scanner v0.0.0-20220816044059-f660fa6a7dc0
go: github.com/google/osv/tools/osv-scanner@latest: module github.com/google/osv/tools/osv-scanner@latest found (v0.0.0-20220816044059-f660fa6a7dc0), but does not contain package github.com/google/osv/tools/osv-scanner
```

OSX
```
liorkesos@mbp-14 ~ % go install github.com/google/osv/tools/osv-scanner@latest
go: downloading github.com/google/osv v0.0.14
go: downloading github.com/google/osv/tools/osv-scanner v0.0.0-20220816044059-f660fa6a7dc0
go: github.com/google/osv/tools/osv-scanner@latest: module github.com/google/osv/tools/osv-scanner@latest found (v0.0.0-20220816044059-f660fa6a7dc0), but does not contain package github.com/google/osv/tools/osv-scanner
```

**Comment by andrewpollock** [comment]
Thanks for surfacing this!

It looks like https://github.com/google/osv.dev/pull/377 only partially implemented a rename, and in hindsight wasn't ideal. We'll rename this directory back and fix up a few references.

**Comment by andrewpollock** [comment]
I think I fixed this with https://github.com/google/osv.dev/pull/785 and #784 is basically a duplicate of this issue.
