### ISSUE TITLE
Generate the ecosystems.txt in the root

### ISSUE THREAD

**Issue by VinodAnandan** [google/osv.dev#619]
Could you please generate the ecosystems.txt in the root that would contain a list of all the ecosystems currently in OSV, from which users can construct URLs to download all advisories for the ecosystems?

**Comment by oliverchang** [comment]
We now have a `https://osv-vulnerabilities.storage.googleapis.com/ecosystems.txt` in the root. 

This still needs to be generated dynamically, but our ecosystems change infrequently so it should be fine to depend on this in the short/medium term.
