### ISSUE TITLE
Add Dart vulnerabilities

### ISSUE THREAD

**Issue by IchordeDionysos** [google/osv.dev#62]
Work with the Dart team to support tracking of Dart Open Source vulnerabilities.

Relates to dart-lang/pub-dev#2160.

**Comment by oliverchang** [comment]
Thanks for connecting us! We would be very happy to have OSV track Dart vulnerabilities. I'll start a conversation with @jonasfj to discuss this.

**Comment by andrewpollock** [comment]
Hi,

We get these (now) by virtue of them being included in GitHub Security Advisories.

c.f. https://osv.dev/list?ecosystem=Pub&q=
