### ISSUE TITLE
main web page on osv.dev, JSON example has an extra comma so it's not valid JSON

### ISSUE THREAD

**Issue by kurtseifried** [google/osv.dev#621]
On the main page at osv.dev in the exmaple:

  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/containers/buildah/commit/..."
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/containers/buildah"
    }
  ],
}

note the comma on the second last line. Breaks the JSON, removal fixes it. Thanks.

**Comment by another-rex** [comment]
Thanks for point this out, #629 should fix this.
