### ISSUE TITLE
PYSEC-2019-144 and GHSA-jhjh-776m-4765 incorrect data

### ISSUE THREAD

**Issue by donchkat** [google/osv.dev#683]
Hi,
PYSEC-2019-144 - I noticed this vulnerability is identified as PYPI, but it's actually a Rust vulnerability in the Rust bindings for the ArrayFire library. I don't see how it's related to PYPI at all.

GHSA-jhjh-776m-4765 - Here the affected versions are far beyond the fixed version.
I'm working with the OSV db data for almost a year now and as far as I know the affected versions are always in the range between the introduced and the fixed versions. 
```[{'package': {'name': 'matrix-synapse', 'ecosystem': 'PyPI', 'purl': 'pkg:pypi/matrix-synapse'}, 'ranges': [{'type': 'ECOSYSTEM', 'events': [{'introduced': '0'}, {'fixed': '1.62'}]}], 'versions': ['0.33.5', '0.33.5.1', '0.33.6', '0.33.6rc1', '0.33.7', '0.33.7rc1', '0.33.7rc2', '0.33.8', '0.33.8rc2', '0.33.9', '0.34.0', '0.34.0.1', '0.34.0rc1', '0.34.0rc2', '0.34.1.1', '0.99.0', '0.99.0rc1', '0.99.0rc2', '0.99.0rc3', '0.99.0rc4', '0.99.1', '0.99.1.1', '0.99.1rc1', '0.99.1rc2', '0.99.2', '0.99.2rc1', '0.99.3', '0.99.3.1', '0.99.3.2', '0.99.3rc1', '0.99.4', '0.99.4rc1', '0.99.5', '0.99.5.1', '0.99.5.2', '0.99.5rc1', '1.0.0', '1.0.0rc1', '1.0.0rc2', '1.0.0rc3', '1.1.0', '1.1.0rc1', '1.1.0rc2', '1.10.0', '1.10.0rc1', '1.10.0rc2', '1.10.0rc3', '1.10.0rc5', '1.10.1', '1.11.0', '1.11.0rc1', '1.11.1', '1.12.0', '1.12.0rc1', '1.12.1', '1.12.1rc1', '1.12.2', '1.12.3', '1.12.4', '1.12.4rc1', '1.13.0', '1.13.0rc1', '1.13.0rc2', '1.13.0rc3', '1.14.0', '1.14.0rc1', '1.14.0rc2', '1.15.0', '1.15.0rc1', '1.15.1', '1.15.2', '1.16.0', '1.16.0rc1', '1.16.0rc2', '1.16.1', '1.17.0', '1.17.0rc1', '1.18.0', '1.18.0rc1', '1.18.0rc2', '1.19.0', '1.19.0rc1', '1.19.1', '1.19.1rc1', '1.19.2', '1.19.3', '1.2.0', '1.2.0rc1', '1.2.0rc2', '1.2.1', '1.20.0', '1.20.0rc1', '1.20.0rc2', '1.20.0rc3', '1.20.0rc4', '1.20.0rc5', '1.20.1', '1.21.0', '1.21.0rc1', '1.21.0rc2', '1.21.0rc3', '1.21.1', '1.21.2', '1.22.0', '1.22.0rc1', '1.22.0rc2', '1.22.1', '1.23.0', '1.23.0rc1', '1.23.1', '1.24.0', '1.24.0rc1', '1.24.0rc2', '1.25.0', '1.25.0rc1', '1.26.0', '1.26.0rc1', '1.26.0rc2', '1.27.0', '1.27.0rc1', '1.27.0rc2', '1.28.0', '1.28.0rc1', '1.29.0', '1.29.0rc1', '1.3.0', '1.3.0rc1', '1.3.1', '1.30.0', '1.30.0rc1', '1.30.1', '1.31.0', '1.31.0rc1', '1.32.0', '1.32.0rc1', '1.32.1', '1.32.2', '1.33.0', '1.33.0rc1', '1.33.0rc2', '1.33.1', '1.33.2', '1.34.0', '1.34.0rc1', '1.35.0', '1.35.0rc1', '1.35.0rc2', '1.35.0rc3', '1.35.1', '1.36.0', '1.36.0rc1', '1.36.0rc2', '1.37.0', '1.37.0rc1', '1.37.1', '1.37.1rc1', '1.38.0', '1.38.0rc1', '1.38.0rc2', '1.38.0rc3', '1.38.1', '1.39.0', '1.39.0rc1', '1.39.0rc2', '1.39.0rc3', '1.4.0', '1.4.0rc1', '1.4.0rc2', '1.4.1', '1.4.1rc1', '1.40.0', '1.40.0rc1', '1.40.0rc2', '1.40.0rc3', '1.41.0', '1.41.0rc1', '1.41.1', '1.42.0', '1.42.0rc1', '1.42.0rc2', '1.43.0', '1.43.0rc1', '1.43.0rc2', '1.44.0', '1.44.0rc1', '1.44.0rc2', '1.44.0rc3', '1.45.0', '1.45.0rc1', '1.45.0rc2', '1.45.1', '1.46.0', '1.46.0rc1', '1.47.0', '1.47.0rc1', '1.47.0rc2', '1.47.0rc3', '1.47.1', '1.48.0', '1.48.0rc1', '1.49.0', '1.49.0rc1', '1.49.2', '1.5.0', '1.5.0rc1', '1.5.0rc2', '1.5.1', '1.50.0', '1.50.0rc1', '1.50.0rc2', '1.50.1', '1.50.2', '1.51.0', '1.51.0rc1', '1.51.0rc2', '1.52.0', '1.52.0rc1', '1.53.0', '1.53.0rc1', '1.54.0', '1.54.0rc1', '1.55.0', '1.55.0rc1', '1.55.1', '1.55.2', '1.56.0', '1.56.0rc1', '1.57.0', '1.57.0rc1', '1.57.1', '1.58.0', '1.58.0rc2', '1.58.1', '1.59.0', '1.59.0rc1', '1.59.0rc2', '1.59.1', '1.6.0', '1.6.0rc1', '1.6.0rc2', '1.6.1', '1.60.0', '1.60.0rc1', '1.60.0rc2', '1.61.0', '1.61.0rc1', '1.61.1', '1.62.0rc1', '1.62.0rc2', '1.62.0rc3', '1.7.0', '1.7.0rc1', '1.7.0rc2', '1.7.1', '1.7.2', '1.7.3', '1.8.0', '1.8.0rc1', '1.9.0', '1.9.0.dev1', '1.9.0.dev2', '1.9.0rc1', '1.9.1'], 'database_specific': {'source': 'https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/08/GHSA-jhjh-776m-4765/GHSA-jhjh-776m-4765.json'}}]```

Let me know if I'm getting something wrong.
Thanks!

**Comment by oliverchang** [comment]
Hi @donchkat,

Re PYSEC-2019-144: Thanks! our automation sometimes makes mistakes -- I've marked this as withdrawn in https://github.com/pypa/advisory-database/pull/99

Re https://github.com/advisories/GHSA-jhjh-776m-4765 -- this appears to be correct? The fixed version is 1.62, which is higher than all the other versions. There's some `1.9.x` versions in there, but `1.9` < `1.62`.

**Comment by donchkat** [comment]
Thanks for the quick answer, it makes sense now.

**Comment by donchkat** [comment]
The withdrawn of PYSEC-2019-144 didn't fix it,  now the identification of the CVE as PyPI ecosystem is coming from GHSA-69fv-gw6g-8ccg which I guess is coming from the GitHub advisory database. I can Open an issue there If you'd like me to.
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/74149435/189679956-54f3c98e-96b2-4298-aaa8-4059ae4f89e2.png">

**Comment by oliverchang** [comment]
Yes, we don't control the GHSA database. I believe you can create a PR there to remove the PyPI package.
