### ISSUE TITLE
Add support for Pub versioning

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#708]
Pub closely follows semver, but unfortunately not exactly: https://pub.dev/packages/pub_semver

**Comment by oliverchang** [comment]
@michaelkedar this is your starter project :) we can talk in detail about it later once you've gotten things set up.

**Comment by michaelkedar** [comment]
Looking at this, the only functional difference seems to be that build suffixes are included in ordering:

> **Version ordering does take build suffixes into account.** This is unlike semver 2.0.0 but like earlier versions of semver. Version `1.2.3+1` is considered a lower number than `1.2.3+2`.
>
>Since a package may have published multiple versions that differ only by build suffix, pub still has to pick one of them _somehow_. Semver leaves that issue unresolved, so we just say that build numbers are sorted like pre-release suffixes.

**Comment by oliverchang** [comment]
> Looking at this, the only functional difference seems to be that build suffixes are included in ordering:
> 
> > **Version ordering does take build suffixes into account.** This is unlike semver 2.0.0 but like earlier versions of semver. Version `1.2.3+1` is considered a lower number than `1.2.3+2`.
> > Since a package may have published multiple versions that differ only by build suffix, pub still has to pick one of them _somehow_. Semver leaves that issue unresolved, so we just say that build numbers are sorted like pre-release suffixes.
> 
> Though unlike pre-release suffixes, a version with build suffixes is considered _later_ than one without:
> 
> > Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0-rc.1+build.1 < 1.0.0 < 1.0.0+0.3.7 < 1.3.7+build < 1.3.7+build.2.b8f12d7 < 1.3.7+build.11.e0f985a.

Is it legal to have **both** a pre-release suffix and build suffix? What are the rules in that case?

**Comment by michaelkedar** [comment]
Yep - that example (from [the spec pub links](https://semver.org/spec/v2.0.0-rc.1.html) has some with both:
> ... < 1.0.0-rc.1 < **1.0.0-rc.1+build.1** < 1.0.0 < 1.0.0+0.3.7 < ...

The pre-release suffix takes precedence over the build suffix
> 12. Precedence MUST be calculated by separating the version into major, minor, patch, pre-release, and build identifiers in that order.
