### ISSUE TITLE
Make /vulnfeeds/cmd/combine-to-osv/run_combine_to_osv_convert.sh support a BYO GCS bucket

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#749]
https://groups.google.com/d/msgid/osv-discuss/72779dd5-cc57-410c-b0cc-6c1568d1c7b3n%40googlegroups.com surfaced that users without read or write access to gs://cve-osv-conversion (a GCS bucket that is only available to OSV developers at Google)

Extend the script so a different bucket can easily be used instead.

**Comment by oliverchang** [comment]
@andrewpollock is this still desired / relevant?

**Comment by andrewpollock** [comment]
I think the previous work done is good enough to call this done.
