### ISSUE TITLE
Go vulnerabilities should have vuln.go.dev instead of storage.googleapis.com as the source

### ISSUE THREAD

**Issue by josieang** [google/osv.dev#787]
For example [osv.dev/vulnerability/GO-2020-0017](https://osv.dev/vulnerability/GO-2020-0017) has [storage.googleapis.com/go-vulndb/ID/GO-2020-0017.json](https://storage.googleapis.com/go-vulndb/ID/GO-2020-0017.json)
as the source. This URL is deprecated, we should be using [vuln.go.dev/ID/GO-2020-0017.json](https://vuln.go.dev/ID/GO-2020-0017.json) instead.

**Comment by oliverchang** [comment]
Done! I updated the `link` property in the corresponding `SourceRepository` entity in OSV.

This will immediately start reflecting in the UI and API (e.g. https://osv.dev/vulnerability/GO-2020-0017), and may take a few hours to propagate to our data dumps.
