### ISSUE TITLE
CVE imports require more advanced last_modified detection

### ISSUE THREAD

**Issue by another-rex** [google/osv.dev#791]
Currently the `last_modified` field is just copied from the original CVE. To have an accurate `last_modified`, we also need to detect modifications in individual affected packages. This logic can be placed in the converter by comparing a previously converted file to the newly converted file, updating the modified date if there is a difference.

**Comment by andrewpollock** [comment]
I filed #2103 as a duplicate of this and @hogo6002 fixed it recently.
