### ISSUE TITLE
Improve separation between ranges

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#797]
From https://osv.dev/vulnerability/PYSEC-2021-100

![image](https://user-images.githubusercontent.com/759062/199853483-a1ae349f-cb82-4d7c-9352-58d35fce8b81.png)

There should be more separation between the "Fixed" part and the next ECOSYSTEM range.

**Comment by chinmaym07** [comment]
HI @oliverchang Can I fix this ?

**Comment by aroramrinaal** [comment]
Hey @oliverchang,
This issue still exists, would love to solve this as my _good-first-issue_.

**Comment by oliverchang** [comment]
Now deployed to the test instance: https://oss-vdb-test.appspot.com/vulnerability/PYSEC-2021-100, and should be included in our next prod release.
