### ISSUE TITLE
Add a News tab with a blog

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#799]
Basic thinking: adding a "News" tab to [osv.dev](http://osv.dev/) and making it an OSV-specific blog for more technical posts less suited to the [Google Security Blog](https://security.googleblog.com/). The example that spawned this thought was communicating about #771 once it's completed.

From an internal conversation about this, @oliverchang said: "this has come up a few times, both from our UX designer and from other folks"

**Comment by oliverchang** [comment]
@lumjjb FYI :)

**Comment by lumjjb** [comment]
🎉 🚀

**Comment by oliverchang** [comment]
We can probably use something like https://github.com/gohugoio/hugo to get a blog going pretty quickly. The only challenge here is getting the styling consistent with osv.dev.
