### ISSUE TITLE
How do we call the API for next_page_token

### ISSUE THREAD

**Issue by athenekuttikkatt** [google/osv.dev#809]
I am getting limited records on the first page of the response. Can you please assist me in calling the API to get the next page content using the next_page_token.  Is this using query string?

**Comment by oliverchang** [comment]
Hi! This is not yet documented for public consumption, but if there is more results to be fetched, the response will include a `page_token`. You may pass this as the `next_page_token` in a subsequent request (and rinse and repeat). 

We'll be refreshing the documentation and including this soon.

**Comment by athenekuttikkatt** [comment]
Hi,

Below is the code 

```
curl --location --request POST 'https://api.osv.dev/v1/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "package": {
        "name": "apache-airflow",
        "ecosystem": "PyPI"
    }
}'
```

I am getting the below section in response 

``` "next_page_token": "Ci8SKWoJbX5vc3MtdmRichwLEgNCdWciE0dIU0EtOHA3di0yanZqLXY1NHIMGAAgAA=="```

I tried the below code with `page_token`

```
curl --location --request POST 'https://api.osv.dev/v1/query?page_token=Ci8SKWoJbX5vc3MtdmRichwLEgNCdWciE0dIU0EtOHA3di0yanZqLXY1NHIMGAAgAA==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "package": {
        "name": "apache-airflow",
        "ecosystem": "PyPI"
    }
}'
```

But this gives 

```upstream connect error or disconnect/reset before headers. reset reason: protocol error```

**Comment by oliverchang** [comment]
You need to pass "page_token" as part of the JSON request, not a URL parameter. 

(Sorry, I just realised I also I wasn't accurate in my last post. "page_token" is the one to set in your subsequent request).
