### ISSUE TITLE
Clarification around OSV's `affected` key

### ISSUE THREAD

**Issue by woodruffw** [google/osv.dev#810]
Hello again!

We're currently trying to expose a couple more OSV fields via `pip-audit`, and @orsinium revealed an inconsistency between the OSV schema docs (https://ossf.github.io/osv-schema/) and the API schema returned by OSV's own API (https://osv.dev/docs/#tag/api/operation/OSV_QueryAffected).

In particular, the schema docs say that clients should not assume the presence of any keys except for `id` and `modified`:

> The id and modified fields are required. All other fields are optional, although of course an entry with no other metadata is not particularly useful. (It could potentially stand for a reserved ID with no other public information.)

Whereas the API schema for `affected` marks it as a required member (linked above, screenshot below):

![Screenshot 2022-11-07 at 10 17 03 AM](https://user-images.githubusercontent.com/3059210/200346205-65996574-dee4-4df5-98ac-54819eacb84e.png)

Am I correct in thinking that `affected` is optional per the spec, and just happens to be required per the current implementation of the API running on `osv.dev`?

**Comment by oliverchang** [comment]
Hi! 

Yes, this is an inconsistency with our API documentation. The OSV schema is the authoritative one. We'll fix this.

**Comment by woodruffw** [comment]
Thanks @oliverchang!

**Comment by oliverchang** [comment]
Closing in favour of https://github.com/google/osv.dev/issues/573
