### ISSUE TITLE
Missing required field in the API's response

### ISSUE THREAD

**Issue by GarlicHiker** [google/osv.dev#862]
Hello,
I found out that for some requests to the API endpoint: `https://api.osv.dev/v1/vulns/<OSV_id>`, the field `summary` is missing inside the response, even though it is marked as **required** according to documentation: https://osv.dev/docs/#tag/api/operation/OSV_GetVulnById

Have a look at response for: https://api.osv.dev/v1/vulns/PYSEC-2021-112

**Comment by oliverchang** [comment]
Hi!

This is an issue with our documentation. The summary field is optional. We'll get this fixed!

**Comment by oliverchang** [comment]
Closing in favour of https://github.com/google/osv.dev/issues/573
