### ISSUE TITLE
API feature request

### ISSUE THREAD

**Issue by lbrossault** [google/osv.dev#873]
Hello,

I would like to clone OSV database on premise (for specific users that don't have internet access from office computers).
Actually we can fetch bulletins specifying product, but here, I would like to get all OSV db.

Regards,

**Comment by andrewpollock** [comment]
Hi, can you elaborate a little more on your requirements? I think we may have a documentation discoverability issue here.

All of the OSV data is available in our GCS bucket, per https://github.com/google/osv.dev#data-dumps but I recognise that this fact is not called out anywhere (obvious, to me) on osv.dev today...

**Comment by lbrossault** [comment]
Hello,


In fact, I would like to:
- Retrieve all (without specifying source (such as PiPy)) OSV data.
- Get latest OSV bulletin in next actions.


Regards,

**Comment by andrewpollock** [comment]
Okay, so you can retrieve all OSV data by doing one of two things:

* `gsutil -m rsync -r gs://osv-vulnerabilities gs://your_gcs_bucket`
* retrieve each ecosystem-specific `all.zip` file from gs://osv-vulnerabilities (see the aforementioned https://github.com/google/osv.dev#data-dumps)

How you then further process or interrogate this data is left as an exercise for the reader.

Can you help me better understand what you mean by "Get latest OSV bulletin in next actions"?
