### ISSUE TITLE
[non-prod] indexer: lots of errors

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#912]
Seeing lots of errors from the indexer:

"failed to process input: datastore: flattening nested structs leads to a slice of slices: field "Hash""

**Comment by oliverchang** [comment]
@susperius FYI!

**Comment by susperius** [comment]
Thanks! Will look into this.

**Comment by oliverchang** [comment]
This is coming from https://github.com/googleapis/google-cloud-go/blob/cf8081fada0955a1682ce3fc400b44bc141309c7/datastore/prop.go#L187

But this check is not correctly accounting for []byte slices, which does not translate to a Datastore Array but rather a singular byte string (Datastore Blob value)

**Comment by oliverchang** [comment]
It looks like a simple patch to fix this on the client library side, not sure if there's some clever way we can get do to get around this.

**Comment by oliverchang** [comment]
Filed https://github.com/googleapis/google-cloud-go/issues/7173 for this. In the meantime we can likely also fork this and patch it ourselves.

**Comment by oliverchang** [comment]
Alternatively, we could potentially also manually flatten this, something like:

```golang
type result struct {                                                                                                                                                                              
        Page        int                      `datastore:"page"`                                                                                                                                   
        Path  []string `datastore:"file_results.path"`
        Hash  [][]byte `datastore:"file_result.hash"`                                                                                                  
}      
```

(untested)
