### ISSUE TITLE
Limitations of OSV DB API

### ISSUE THREAD

**Issue by sourabhsparkala** [google/osv.dev#931]
Hello All, I am creating this issue to raise a question on the limitations of OSV DB API.
- For example, GitHub APIs have restrictions on the number of request calls that can be made with a specific User access token in an hour.
- If there are restrictions, what should the user do to overcome such limits? Whom do you contact regarding this?
- I observed that `https://api.osv.dev/v1/querybatch` API call with multiple queries, returns only a list of GitHub advisories, should it not return the complete vulnerability object with CVE, impact, severity and other infos? Are we missing something here?

Please find my curl sample, as you can see below, the result is just a flat list of GitHub advisories
```
curl --location --request POST 'https://api.osv.dev/v1/querybatch' \
--header 'Content-Type: application/json' \
--data-raw '{
   "queries":[
        {
            "version":"2.12.6",
            "package": {
                "name": "com.fasterxml.jackson.core:jackson-databind", 
                "ecosystem": "Maven"
            }
        },
        {
            "version": "1.59",
            "package":{
               "name":"org.bouncycastle:bcprov-jdk15on",
               "ecosystem":"Maven"
        }
      }
   ]
}'


Output:
{
    "results": [
        {
            "vulns": [
                {
                    "id": "GHSA-57j2-w4cx-62h2",
                    "modified": "2022-12-14T05:10:13.978383Z"
                },
                {
                    "id": "GHSA-jjjh-jjxp-wpff",
                    "modified": "2022-12-14T05:29:48.906253Z"
                },
                {
                    "id": "GHSA-rgv9-q543-rqg4",
                    "modified": "2022-12-14T05:06:42.513025Z"
                }
            ]
        },
        {
            "vulns": [
                {
                    "id": "GHSA-6xx3-rg99-gc3p",
                    "modified": "2022-12-14T04:57:02.505254Z"
                }
            ]
        }
    ]
}
```

Please let me know if this is the right forum to post the questions.

Thanks
Sourabh

**Comment by oliverchang** [comment]
Hi!

There are currently no rate limits for our API.

Re the `querybatch` question: The responses are not hydrated -- you would need to make separate `GET` requests to retrieve the full vulnerability objects. Our auto-generated documentation unfortunately lacks this detail -- this will be solved as part of  https://github.com/google/osv.dev/issues/573
