### ISSUE TITLE
Can't press backspace in search bar

### ISSUE THREAD

**Issue by di** [google/osv.dev#938]
At https://osv.dev/list, when typing in the "package or ID search" bar, I can't press backspace to remove a character.

I can only reproduce this with Chrome (Version 108.0.5359.124). It works as expected in Firefox. My platform is macOS.

**Comment by andrewpollock** [comment]
That's a fun one.

Certainly sounds like a Chrome bug. I can't reproduce it with 108.0.5359.111 on ChromeOS

I'll see if I can find any relevant Chrome bugs for this already.

Looking at https://chromiumdash.appspot.com/releases?platform=Mac, would you be willing to try the Beta track to see if it's still present there in the meantime?

**Comment by andrewpollock** [comment]
Nothing obvious is jumping out at me at https://bugs.chromium.org/p/chromium/issues/list?q=backspace%20OS%3DMac&can=2

**Comment by di** [comment]
🤷 works now! Must have been an intermittent thing with my browser.
