### ISSUE TITLE
Add public documentation for each data source

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#948]
The table of prefixes at https://ossf.github.io/osv-schema/ is the most canonical documentation we have for current sources of vulnerabilities that OSV uses.

Expand this to include a point of contact or feedback channel in the event of receiving questionable data. One possibility is a page per source, and a link to that page from each row of this table.

**Comment by hayleycd** [comment]
@andrewpollock can you expand a little bit more on what you are envisioning and where it would go?

I suppose it is more than adding the database source links to https://github.com/google/osv.dev#current-data-sources. 

It also sounds like maybe you want the schema docs edited, but this is an issue on the OSV.dev repo, so I am not sure if I am just misunderstanding.

**Comment by andrewpollock** [comment]
I think we can close this one, we've got some point of contact info in our internal who's who spreadsheet, and when we get a more defined end-user per-record data feedback mechanism in place, that will go straight back to the source.
