### ISSUE TITLE
Make the ability to download the entire database from GCB clearer on osv.dev

### ISSUE THREAD

**Issue by another-rex** [google/osv.dev#998]
I was just looking at osv.dev, and neither the FAQ and the main page show that the entire database can be downloaded from the cloud buckets.

**Comment by andrewpollock** [comment]
My thoughts:

* Add an FAQ entry at https://osv.dev/about to the effect of "How can I get the data?"
* Add an additional red button at the top of the front page "Download the data" that links to this FAQ entry

**Comment by andrewpollock** [comment]
Optional extra: write an OSV blog post about the data being readily available.

**Comment by andrewpollock** [comment]
Essentially replicate the content at https://github.com/google/osv.dev#data-dumps
